// Code generated by ent, DO NOT EDIT.

package finding

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"librevita.org/internal/database/record/predicate"
	"librevita.org/pkg/ident"
)

// ID filters vertices based on their ID field.
func ID(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ident.FindingID) predicate.Finding {
	return predicate.Finding(sql.FieldLTE(FieldID, id))
}

// ClinicID applies equality check predicate on the "clinic_id" field. It's identical to ClinicIDEQ.
func ClinicID(v ident.ClinicID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldClinicID, v))
}

// PatientID applies equality check predicate on the "patient_id" field. It's identical to PatientIDEQ.
func PatientID(v ident.PatientID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldPatientID, v))
}

// EpisodeID applies equality check predicate on the "episode_id" field. It's identical to EpisodeIDEQ.
func EpisodeID(v ident.EpisodeID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldEpisodeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldUpdatedAt, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldEffectiveAt, v))
}

// CodeSystem applies equality check predicate on the "code_system" field. It's identical to CodeSystemEQ.
func CodeSystem(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldCodeSystem, vc), err)
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldCode, vc), err)
}

// Display applies equality check predicate on the "display" field. It's identical to DisplayEQ.
func Display(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldDisplay, vc), err)
}

// ValueNumber applies equality check predicate on the "value_number" field. It's identical to ValueNumberEQ.
func ValueNumber(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueNumber, vc), err)
}

// ValueUnit applies equality check predicate on the "value_unit" field. It's identical to ValueUnitEQ.
func ValueUnit(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueUnit, vc), err)
}

// ValueUcum applies equality check predicate on the "value_ucum" field. It's identical to ValueUcumEQ.
func ValueUcum(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueUcum, vc), err)
}

// ValueText applies equality check predicate on the "value_text" field. It's identical to ValueTextEQ.
func ValueText(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueText, vc), err)
}

// ValueBool applies equality check predicate on the "value_bool" field. It's identical to ValueBoolEQ.
func ValueBool(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueBool, vc), err)
}

// ValueCodedSystem applies equality check predicate on the "value_coded_system" field. It's identical to ValueCodedSystemEQ.
func ValueCodedSystem(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedSystem, vc), err)
}

// ValueCodedCode applies equality check predicate on the "value_coded_code" field. It's identical to ValueCodedCodeEQ.
func ValueCodedCode(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedCode, vc), err)
}

// ValueCodedDisplay applies equality check predicate on the "value_coded_display" field. It's identical to ValueCodedDisplayEQ.
func ValueCodedDisplay(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedDisplay, vc), err)
}

// CodeBlindIndex applies equality check predicate on the "code_blind_index" field. It's identical to CodeBlindIndexEQ.
func CodeBlindIndex(v string) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldCodeBlindIndex, v))
}

// ClinicIDEQ applies the EQ predicate on the "clinic_id" field.
func ClinicIDEQ(v ident.ClinicID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldClinicID, v))
}

// ClinicIDNEQ applies the NEQ predicate on the "clinic_id" field.
func ClinicIDNEQ(v ident.ClinicID) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldClinicID, v))
}

// ClinicIDIn applies the In predicate on the "clinic_id" field.
func ClinicIDIn(vs ...ident.ClinicID) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldClinicID, vs...))
}

// ClinicIDNotIn applies the NotIn predicate on the "clinic_id" field.
func ClinicIDNotIn(vs ...ident.ClinicID) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldClinicID, vs...))
}

// PatientIDEQ applies the EQ predicate on the "patient_id" field.
func PatientIDEQ(v ident.PatientID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldPatientID, v))
}

// PatientIDNEQ applies the NEQ predicate on the "patient_id" field.
func PatientIDNEQ(v ident.PatientID) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldPatientID, v))
}

// PatientIDIn applies the In predicate on the "patient_id" field.
func PatientIDIn(vs ...ident.PatientID) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldPatientID, vs...))
}

// PatientIDNotIn applies the NotIn predicate on the "patient_id" field.
func PatientIDNotIn(vs ...ident.PatientID) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldPatientID, vs...))
}

// EpisodeIDEQ applies the EQ predicate on the "episode_id" field.
func EpisodeIDEQ(v ident.EpisodeID) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldEpisodeID, v))
}

// EpisodeIDNEQ applies the NEQ predicate on the "episode_id" field.
func EpisodeIDNEQ(v ident.EpisodeID) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldEpisodeID, v))
}

// EpisodeIDIn applies the In predicate on the "episode_id" field.
func EpisodeIDIn(vs ...ident.EpisodeID) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldEpisodeID, vs...))
}

// EpisodeIDNotIn applies the NotIn predicate on the "episode_id" field.
func EpisodeIDNotIn(vs ...ident.EpisodeID) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldEpisodeID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldStatus, vs...))
}

// ValueKindEQ applies the EQ predicate on the "value_kind" field.
func ValueKindEQ(v ValueKind) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldValueKind, v))
}

// ValueKindNEQ applies the NEQ predicate on the "value_kind" field.
func ValueKindNEQ(v ValueKind) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldValueKind, v))
}

// ValueKindIn applies the In predicate on the "value_kind" field.
func ValueKindIn(vs ...ValueKind) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldValueKind, vs...))
}

// ValueKindNotIn applies the NotIn predicate on the "value_kind" field.
func ValueKindNotIn(vs ...ValueKind) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldValueKind, vs...))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.Finding {
	return predicate.Finding(sql.FieldLTE(FieldEffectiveAt, v))
}

// CodeSystemEQ applies the EQ predicate on the "code_system" field.
func CodeSystemEQ(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldCodeSystem, vc), err)
}

// CodeSystemNEQ applies the NEQ predicate on the "code_system" field.
func CodeSystemNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldCodeSystem, vc), err)
}

// CodeSystemIn applies the In predicate on the "code_system" field.
func CodeSystemIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.CodeSystem.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldCodeSystem, v...), err)
}

// CodeSystemNotIn applies the NotIn predicate on the "code_system" field.
func CodeSystemNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.CodeSystem.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldCodeSystem, v...), err)
}

// CodeSystemGT applies the GT predicate on the "code_system" field.
func CodeSystemGT(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldCodeSystem, vc), err)
}

// CodeSystemGTE applies the GTE predicate on the "code_system" field.
func CodeSystemGTE(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldCodeSystem, vc), err)
}

// CodeSystemLT applies the LT predicate on the "code_system" field.
func CodeSystemLT(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldCodeSystem, vc), err)
}

// CodeSystemLTE applies the LTE predicate on the "code_system" field.
func CodeSystemLTE(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldCodeSystem, vc), err)
}

// CodeSystemContains applies the Contains predicate on the "code_system" field.
func CodeSystemContains(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldCodeSystem, vcs), err)
}

// CodeSystemHasPrefix applies the HasPrefix predicate on the "code_system" field.
func CodeSystemHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldCodeSystem, vcs), err)
}

// CodeSystemHasSuffix applies the HasSuffix predicate on the "code_system" field.
func CodeSystemHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldCodeSystem, vcs), err)
}

// CodeSystemIsNil applies the IsNil predicate on the "code_system" field.
func CodeSystemIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldCodeSystem))
}

// CodeSystemNotNil applies the NotNil predicate on the "code_system" field.
func CodeSystemNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldCodeSystem))
}

// CodeSystemEqualFold applies the EqualFold predicate on the "code_system" field.
func CodeSystemEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldCodeSystem, vcs), err)
}

// CodeSystemContainsFold applies the ContainsFold predicate on the "code_system" field.
func CodeSystemContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.CodeSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldCodeSystem, vcs), err)
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldCode, vc), err)
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldCode, vc), err)
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Code.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldCode, v...), err)
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Code.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldCode, v...), err)
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldCode, vc), err)
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldCode, vc), err)
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldCode, vc), err)
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldCode, vc), err)
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldCode, vcs), err)
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldCode, vcs), err)
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldCode, vcs), err)
}

// CodeIsNil applies the IsNil predicate on the "code" field.
func CodeIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldCode))
}

// CodeNotNil applies the NotNil predicate on the "code" field.
func CodeNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldCode))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldCode, vcs), err)
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.Code.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldCode, vcs), err)
}

// DisplayEQ applies the EQ predicate on the "display" field.
func DisplayEQ(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldDisplay, vc), err)
}

// DisplayNEQ applies the NEQ predicate on the "display" field.
func DisplayNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldDisplay, vc), err)
}

// DisplayIn applies the In predicate on the "display" field.
func DisplayIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Display.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldDisplay, v...), err)
}

// DisplayNotIn applies the NotIn predicate on the "display" field.
func DisplayNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Display.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldDisplay, v...), err)
}

// DisplayGT applies the GT predicate on the "display" field.
func DisplayGT(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldDisplay, vc), err)
}

// DisplayGTE applies the GTE predicate on the "display" field.
func DisplayGTE(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldDisplay, vc), err)
}

// DisplayLT applies the LT predicate on the "display" field.
func DisplayLT(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldDisplay, vc), err)
}

// DisplayLTE applies the LTE predicate on the "display" field.
func DisplayLTE(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldDisplay, vc), err)
}

// DisplayContains applies the Contains predicate on the "display" field.
func DisplayContains(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldDisplay, vcs), err)
}

// DisplayHasPrefix applies the HasPrefix predicate on the "display" field.
func DisplayHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldDisplay, vcs), err)
}

// DisplayHasSuffix applies the HasSuffix predicate on the "display" field.
func DisplayHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldDisplay, vcs), err)
}

// DisplayIsNil applies the IsNil predicate on the "display" field.
func DisplayIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldDisplay))
}

// DisplayNotNil applies the NotNil predicate on the "display" field.
func DisplayNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldDisplay))
}

// DisplayEqualFold applies the EqualFold predicate on the "display" field.
func DisplayEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldDisplay, vcs), err)
}

// DisplayContainsFold applies the ContainsFold predicate on the "display" field.
func DisplayContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.Display.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldDisplay, vcs), err)
}

// ValueNumberEQ applies the EQ predicate on the "value_number" field.
func ValueNumberEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueNumber, vc), err)
}

// ValueNumberNEQ applies the NEQ predicate on the "value_number" field.
func ValueNumberNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueNumber, vc), err)
}

// ValueNumberIn applies the In predicate on the "value_number" field.
func ValueNumberIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueNumber.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueNumber, v...), err)
}

// ValueNumberNotIn applies the NotIn predicate on the "value_number" field.
func ValueNumberNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueNumber.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueNumber, v...), err)
}

// ValueNumberGT applies the GT predicate on the "value_number" field.
func ValueNumberGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueNumber, vc), err)
}

// ValueNumberGTE applies the GTE predicate on the "value_number" field.
func ValueNumberGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueNumber, vc), err)
}

// ValueNumberLT applies the LT predicate on the "value_number" field.
func ValueNumberLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueNumber, vc), err)
}

// ValueNumberLTE applies the LTE predicate on the "value_number" field.
func ValueNumberLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueNumber, vc), err)
}

// ValueNumberContains applies the Contains predicate on the "value_number" field.
func ValueNumberContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_number value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueNumber, vcs), err)
}

// ValueNumberHasPrefix applies the HasPrefix predicate on the "value_number" field.
func ValueNumberHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_number value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueNumber, vcs), err)
}

// ValueNumberHasSuffix applies the HasSuffix predicate on the "value_number" field.
func ValueNumberHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_number value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueNumber, vcs), err)
}

// ValueNumberIsNil applies the IsNil predicate on the "value_number" field.
func ValueNumberIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueNumber))
}

// ValueNumberNotNil applies the NotNil predicate on the "value_number" field.
func ValueNumberNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueNumber))
}

// ValueNumberEqualFold applies the EqualFold predicate on the "value_number" field.
func ValueNumberEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_number value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueNumber, vcs), err)
}

// ValueNumberContainsFold applies the ContainsFold predicate on the "value_number" field.
func ValueNumberContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueNumber.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_number value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueNumber, vcs), err)
}

// ValueUnitEQ applies the EQ predicate on the "value_unit" field.
func ValueUnitEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueUnit, vc), err)
}

// ValueUnitNEQ applies the NEQ predicate on the "value_unit" field.
func ValueUnitNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueUnit, vc), err)
}

// ValueUnitIn applies the In predicate on the "value_unit" field.
func ValueUnitIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueUnit.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueUnit, v...), err)
}

// ValueUnitNotIn applies the NotIn predicate on the "value_unit" field.
func ValueUnitNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueUnit.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueUnit, v...), err)
}

// ValueUnitGT applies the GT predicate on the "value_unit" field.
func ValueUnitGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueUnit, vc), err)
}

// ValueUnitGTE applies the GTE predicate on the "value_unit" field.
func ValueUnitGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueUnit, vc), err)
}

// ValueUnitLT applies the LT predicate on the "value_unit" field.
func ValueUnitLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueUnit, vc), err)
}

// ValueUnitLTE applies the LTE predicate on the "value_unit" field.
func ValueUnitLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueUnit, vc), err)
}

// ValueUnitContains applies the Contains predicate on the "value_unit" field.
func ValueUnitContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_unit value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueUnit, vcs), err)
}

// ValueUnitHasPrefix applies the HasPrefix predicate on the "value_unit" field.
func ValueUnitHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_unit value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueUnit, vcs), err)
}

// ValueUnitHasSuffix applies the HasSuffix predicate on the "value_unit" field.
func ValueUnitHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_unit value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueUnit, vcs), err)
}

// ValueUnitIsNil applies the IsNil predicate on the "value_unit" field.
func ValueUnitIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueUnit))
}

// ValueUnitNotNil applies the NotNil predicate on the "value_unit" field.
func ValueUnitNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueUnit))
}

// ValueUnitEqualFold applies the EqualFold predicate on the "value_unit" field.
func ValueUnitEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_unit value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueUnit, vcs), err)
}

// ValueUnitContainsFold applies the ContainsFold predicate on the "value_unit" field.
func ValueUnitContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUnit.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_unit value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueUnit, vcs), err)
}

// ValueUcumEQ applies the EQ predicate on the "value_ucum" field.
func ValueUcumEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueUcum, vc), err)
}

// ValueUcumNEQ applies the NEQ predicate on the "value_ucum" field.
func ValueUcumNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueUcum, vc), err)
}

// ValueUcumIn applies the In predicate on the "value_ucum" field.
func ValueUcumIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueUcum.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueUcum, v...), err)
}

// ValueUcumNotIn applies the NotIn predicate on the "value_ucum" field.
func ValueUcumNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueUcum.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueUcum, v...), err)
}

// ValueUcumGT applies the GT predicate on the "value_ucum" field.
func ValueUcumGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueUcum, vc), err)
}

// ValueUcumGTE applies the GTE predicate on the "value_ucum" field.
func ValueUcumGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueUcum, vc), err)
}

// ValueUcumLT applies the LT predicate on the "value_ucum" field.
func ValueUcumLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueUcum, vc), err)
}

// ValueUcumLTE applies the LTE predicate on the "value_ucum" field.
func ValueUcumLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueUcum, vc), err)
}

// ValueUcumContains applies the Contains predicate on the "value_ucum" field.
func ValueUcumContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_ucum value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueUcum, vcs), err)
}

// ValueUcumHasPrefix applies the HasPrefix predicate on the "value_ucum" field.
func ValueUcumHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_ucum value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueUcum, vcs), err)
}

// ValueUcumHasSuffix applies the HasSuffix predicate on the "value_ucum" field.
func ValueUcumHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_ucum value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueUcum, vcs), err)
}

// ValueUcumIsNil applies the IsNil predicate on the "value_ucum" field.
func ValueUcumIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueUcum))
}

// ValueUcumNotNil applies the NotNil predicate on the "value_ucum" field.
func ValueUcumNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueUcum))
}

// ValueUcumEqualFold applies the EqualFold predicate on the "value_ucum" field.
func ValueUcumEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_ucum value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueUcum, vcs), err)
}

// ValueUcumContainsFold applies the ContainsFold predicate on the "value_ucum" field.
func ValueUcumContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueUcum.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_ucum value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueUcum, vcs), err)
}

// ValueTextEQ applies the EQ predicate on the "value_text" field.
func ValueTextEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueText, vc), err)
}

// ValueTextNEQ applies the NEQ predicate on the "value_text" field.
func ValueTextNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueText, vc), err)
}

// ValueTextIn applies the In predicate on the "value_text" field.
func ValueTextIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueText.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueText, v...), err)
}

// ValueTextNotIn applies the NotIn predicate on the "value_text" field.
func ValueTextNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueText.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueText, v...), err)
}

// ValueTextGT applies the GT predicate on the "value_text" field.
func ValueTextGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueText, vc), err)
}

// ValueTextGTE applies the GTE predicate on the "value_text" field.
func ValueTextGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueText, vc), err)
}

// ValueTextLT applies the LT predicate on the "value_text" field.
func ValueTextLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueText, vc), err)
}

// ValueTextLTE applies the LTE predicate on the "value_text" field.
func ValueTextLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueText, vc), err)
}

// ValueTextContains applies the Contains predicate on the "value_text" field.
func ValueTextContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_text value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueText, vcs), err)
}

// ValueTextHasPrefix applies the HasPrefix predicate on the "value_text" field.
func ValueTextHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_text value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueText, vcs), err)
}

// ValueTextHasSuffix applies the HasSuffix predicate on the "value_text" field.
func ValueTextHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_text value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueText, vcs), err)
}

// ValueTextIsNil applies the IsNil predicate on the "value_text" field.
func ValueTextIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueText))
}

// ValueTextNotNil applies the NotNil predicate on the "value_text" field.
func ValueTextNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueText))
}

// ValueTextEqualFold applies the EqualFold predicate on the "value_text" field.
func ValueTextEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_text value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueText, vcs), err)
}

// ValueTextContainsFold applies the ContainsFold predicate on the "value_text" field.
func ValueTextContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueText.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_text value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueText, vcs), err)
}

// ValueBoolEQ applies the EQ predicate on the "value_bool" field.
func ValueBoolEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueBool, vc), err)
}

// ValueBoolNEQ applies the NEQ predicate on the "value_bool" field.
func ValueBoolNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueBool, vc), err)
}

// ValueBoolIn applies the In predicate on the "value_bool" field.
func ValueBoolIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueBool.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueBool, v...), err)
}

// ValueBoolNotIn applies the NotIn predicate on the "value_bool" field.
func ValueBoolNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueBool.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueBool, v...), err)
}

// ValueBoolGT applies the GT predicate on the "value_bool" field.
func ValueBoolGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueBool, vc), err)
}

// ValueBoolGTE applies the GTE predicate on the "value_bool" field.
func ValueBoolGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueBool, vc), err)
}

// ValueBoolLT applies the LT predicate on the "value_bool" field.
func ValueBoolLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueBool, vc), err)
}

// ValueBoolLTE applies the LTE predicate on the "value_bool" field.
func ValueBoolLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueBool, vc), err)
}

// ValueBoolContains applies the Contains predicate on the "value_bool" field.
func ValueBoolContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_bool value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueBool, vcs), err)
}

// ValueBoolHasPrefix applies the HasPrefix predicate on the "value_bool" field.
func ValueBoolHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_bool value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueBool, vcs), err)
}

// ValueBoolHasSuffix applies the HasSuffix predicate on the "value_bool" field.
func ValueBoolHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_bool value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueBool, vcs), err)
}

// ValueBoolIsNil applies the IsNil predicate on the "value_bool" field.
func ValueBoolIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueBool))
}

// ValueBoolNotNil applies the NotNil predicate on the "value_bool" field.
func ValueBoolNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueBool))
}

// ValueBoolEqualFold applies the EqualFold predicate on the "value_bool" field.
func ValueBoolEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_bool value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueBool, vcs), err)
}

// ValueBoolContainsFold applies the ContainsFold predicate on the "value_bool" field.
func ValueBoolContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueBool.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_bool value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueBool, vcs), err)
}

// ValueCodedSystemEQ applies the EQ predicate on the "value_coded_system" field.
func ValueCodedSystemEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemNEQ applies the NEQ predicate on the "value_coded_system" field.
func ValueCodedSystemNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemIn applies the In predicate on the "value_coded_system" field.
func ValueCodedSystemIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedSystem.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueCodedSystem, v...), err)
}

// ValueCodedSystemNotIn applies the NotIn predicate on the "value_coded_system" field.
func ValueCodedSystemNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedSystem.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueCodedSystem, v...), err)
}

// ValueCodedSystemGT applies the GT predicate on the "value_coded_system" field.
func ValueCodedSystemGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemGTE applies the GTE predicate on the "value_coded_system" field.
func ValueCodedSystemGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemLT applies the LT predicate on the "value_coded_system" field.
func ValueCodedSystemLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemLTE applies the LTE predicate on the "value_coded_system" field.
func ValueCodedSystemLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueCodedSystem, vc), err)
}

// ValueCodedSystemContains applies the Contains predicate on the "value_coded_system" field.
func ValueCodedSystemContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueCodedSystem, vcs), err)
}

// ValueCodedSystemHasPrefix applies the HasPrefix predicate on the "value_coded_system" field.
func ValueCodedSystemHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueCodedSystem, vcs), err)
}

// ValueCodedSystemHasSuffix applies the HasSuffix predicate on the "value_coded_system" field.
func ValueCodedSystemHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueCodedSystem, vcs), err)
}

// ValueCodedSystemIsNil applies the IsNil predicate on the "value_coded_system" field.
func ValueCodedSystemIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueCodedSystem))
}

// ValueCodedSystemNotNil applies the NotNil predicate on the "value_coded_system" field.
func ValueCodedSystemNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueCodedSystem))
}

// ValueCodedSystemEqualFold applies the EqualFold predicate on the "value_coded_system" field.
func ValueCodedSystemEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueCodedSystem, vcs), err)
}

// ValueCodedSystemContainsFold applies the ContainsFold predicate on the "value_coded_system" field.
func ValueCodedSystemContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedSystem.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_system value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueCodedSystem, vcs), err)
}

// ValueCodedCodeEQ applies the EQ predicate on the "value_coded_code" field.
func ValueCodedCodeEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeNEQ applies the NEQ predicate on the "value_coded_code" field.
func ValueCodedCodeNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeIn applies the In predicate on the "value_coded_code" field.
func ValueCodedCodeIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedCode.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueCodedCode, v...), err)
}

// ValueCodedCodeNotIn applies the NotIn predicate on the "value_coded_code" field.
func ValueCodedCodeNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedCode.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueCodedCode, v...), err)
}

// ValueCodedCodeGT applies the GT predicate on the "value_coded_code" field.
func ValueCodedCodeGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeGTE applies the GTE predicate on the "value_coded_code" field.
func ValueCodedCodeGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeLT applies the LT predicate on the "value_coded_code" field.
func ValueCodedCodeLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeLTE applies the LTE predicate on the "value_coded_code" field.
func ValueCodedCodeLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueCodedCode, vc), err)
}

// ValueCodedCodeContains applies the Contains predicate on the "value_coded_code" field.
func ValueCodedCodeContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueCodedCode, vcs), err)
}

// ValueCodedCodeHasPrefix applies the HasPrefix predicate on the "value_coded_code" field.
func ValueCodedCodeHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueCodedCode, vcs), err)
}

// ValueCodedCodeHasSuffix applies the HasSuffix predicate on the "value_coded_code" field.
func ValueCodedCodeHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueCodedCode, vcs), err)
}

// ValueCodedCodeIsNil applies the IsNil predicate on the "value_coded_code" field.
func ValueCodedCodeIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueCodedCode))
}

// ValueCodedCodeNotNil applies the NotNil predicate on the "value_coded_code" field.
func ValueCodedCodeNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueCodedCode))
}

// ValueCodedCodeEqualFold applies the EqualFold predicate on the "value_coded_code" field.
func ValueCodedCodeEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueCodedCode, vcs), err)
}

// ValueCodedCodeContainsFold applies the ContainsFold predicate on the "value_coded_code" field.
func ValueCodedCodeContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedCode.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_code value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueCodedCode, vcs), err)
}

// ValueCodedDisplayEQ applies the EQ predicate on the "value_coded_display" field.
func ValueCodedDisplayEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldEQ(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayNEQ applies the NEQ predicate on the "value_coded_display" field.
func ValueCodedDisplayNEQ(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldNEQ(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayIn applies the In predicate on the "value_coded_display" field.
func ValueCodedDisplayIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedDisplay.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldIn(FieldValueCodedDisplay, v...), err)
}

// ValueCodedDisplayNotIn applies the NotIn predicate on the "value_coded_display" field.
func ValueCodedDisplayNotIn(vs ...string) predicate.Finding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.ValueCodedDisplay.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.FindingOrErr(sql.FieldNotIn(FieldValueCodedDisplay, v...), err)
}

// ValueCodedDisplayGT applies the GT predicate on the "value_coded_display" field.
func ValueCodedDisplayGT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldGT(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayGTE applies the GTE predicate on the "value_coded_display" field.
func ValueCodedDisplayGTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldGTE(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayLT applies the LT predicate on the "value_coded_display" field.
func ValueCodedDisplayLT(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldLT(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayLTE applies the LTE predicate on the "value_coded_display" field.
func ValueCodedDisplayLTE(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	return predicate.FindingOrErr(sql.FieldLTE(FieldValueCodedDisplay, vc), err)
}

// ValueCodedDisplayContains applies the Contains predicate on the "value_coded_display" field.
func ValueCodedDisplayContains(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContains(FieldValueCodedDisplay, vcs), err)
}

// ValueCodedDisplayHasPrefix applies the HasPrefix predicate on the "value_coded_display" field.
func ValueCodedDisplayHasPrefix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasPrefix(FieldValueCodedDisplay, vcs), err)
}

// ValueCodedDisplayHasSuffix applies the HasSuffix predicate on the "value_coded_display" field.
func ValueCodedDisplayHasSuffix(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldHasSuffix(FieldValueCodedDisplay, vcs), err)
}

// ValueCodedDisplayIsNil applies the IsNil predicate on the "value_coded_display" field.
func ValueCodedDisplayIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldValueCodedDisplay))
}

// ValueCodedDisplayNotNil applies the NotNil predicate on the "value_coded_display" field.
func ValueCodedDisplayNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldValueCodedDisplay))
}

// ValueCodedDisplayEqualFold applies the EqualFold predicate on the "value_coded_display" field.
func ValueCodedDisplayEqualFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldEqualFold(FieldValueCodedDisplay, vcs), err)
}

// ValueCodedDisplayContainsFold applies the ContainsFold predicate on the "value_coded_display" field.
func ValueCodedDisplayContainsFold(v string) predicate.Finding {
	vc, err := ValueScanner.ValueCodedDisplay.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("value_coded_display value is not a string: %T", vc)
	}
	return predicate.FindingOrErr(sql.FieldContainsFold(FieldValueCodedDisplay, vcs), err)
}

// CodeBlindIndexEQ applies the EQ predicate on the "code_blind_index" field.
func CodeBlindIndexEQ(v string) predicate.Finding {
	return predicate.Finding(sql.FieldEQ(FieldCodeBlindIndex, v))
}

// CodeBlindIndexNEQ applies the NEQ predicate on the "code_blind_index" field.
func CodeBlindIndexNEQ(v string) predicate.Finding {
	return predicate.Finding(sql.FieldNEQ(FieldCodeBlindIndex, v))
}

// CodeBlindIndexIn applies the In predicate on the "code_blind_index" field.
func CodeBlindIndexIn(vs ...string) predicate.Finding {
	return predicate.Finding(sql.FieldIn(FieldCodeBlindIndex, vs...))
}

// CodeBlindIndexNotIn applies the NotIn predicate on the "code_blind_index" field.
func CodeBlindIndexNotIn(vs ...string) predicate.Finding {
	return predicate.Finding(sql.FieldNotIn(FieldCodeBlindIndex, vs...))
}

// CodeBlindIndexGT applies the GT predicate on the "code_blind_index" field.
func CodeBlindIndexGT(v string) predicate.Finding {
	return predicate.Finding(sql.FieldGT(FieldCodeBlindIndex, v))
}

// CodeBlindIndexGTE applies the GTE predicate on the "code_blind_index" field.
func CodeBlindIndexGTE(v string) predicate.Finding {
	return predicate.Finding(sql.FieldGTE(FieldCodeBlindIndex, v))
}

// CodeBlindIndexLT applies the LT predicate on the "code_blind_index" field.
func CodeBlindIndexLT(v string) predicate.Finding {
	return predicate.Finding(sql.FieldLT(FieldCodeBlindIndex, v))
}

// CodeBlindIndexLTE applies the LTE predicate on the "code_blind_index" field.
func CodeBlindIndexLTE(v string) predicate.Finding {
	return predicate.Finding(sql.FieldLTE(FieldCodeBlindIndex, v))
}

// CodeBlindIndexContains applies the Contains predicate on the "code_blind_index" field.
func CodeBlindIndexContains(v string) predicate.Finding {
	return predicate.Finding(sql.FieldContains(FieldCodeBlindIndex, v))
}

// CodeBlindIndexHasPrefix applies the HasPrefix predicate on the "code_blind_index" field.
func CodeBlindIndexHasPrefix(v string) predicate.Finding {
	return predicate.Finding(sql.FieldHasPrefix(FieldCodeBlindIndex, v))
}

// CodeBlindIndexHasSuffix applies the HasSuffix predicate on the "code_blind_index" field.
func CodeBlindIndexHasSuffix(v string) predicate.Finding {
	return predicate.Finding(sql.FieldHasSuffix(FieldCodeBlindIndex, v))
}

// CodeBlindIndexIsNil applies the IsNil predicate on the "code_blind_index" field.
func CodeBlindIndexIsNil() predicate.Finding {
	return predicate.Finding(sql.FieldIsNull(FieldCodeBlindIndex))
}

// CodeBlindIndexNotNil applies the NotNil predicate on the "code_blind_index" field.
func CodeBlindIndexNotNil() predicate.Finding {
	return predicate.Finding(sql.FieldNotNull(FieldCodeBlindIndex))
}

// CodeBlindIndexEqualFold applies the EqualFold predicate on the "code_blind_index" field.
func CodeBlindIndexEqualFold(v string) predicate.Finding {
	return predicate.Finding(sql.FieldEqualFold(FieldCodeBlindIndex, v))
}

// CodeBlindIndexContainsFold applies the ContainsFold predicate on the "code_blind_index" field.
func CodeBlindIndexContainsFold(v string) predicate.Finding {
	return predicate.Finding(sql.FieldContainsFold(FieldCodeBlindIndex, v))
}

// HasClinic applies the HasEdge predicate on the "clinic" edge.
func HasClinic() predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClinicTable, ClinicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicWith applies the HasEdge predicate on the "clinic" edge with a given conditions (other predicates).
func HasClinicWith(preds ...predicate.Clinic) predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := newClinicStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPatient applies the HasEdge predicate on the "patient" edge.
func HasPatient() predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientWith applies the HasEdge predicate on the "patient" edge with a given conditions (other predicates).
func HasPatientWith(preds ...predicate.Patient) predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := newPatientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEpisode applies the HasEdge predicate on the "episode" edge.
func HasEpisode() predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EpisodeTable, EpisodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEpisodeWith applies the HasEdge predicate on the "episode" edge with a given conditions (other predicates).
func HasEpisodeWith(preds ...predicate.Episode) predicate.Finding {
	return predicate.Finding(func(s *sql.Selector) {
		step := newEpisodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Finding) predicate.Finding {
	return predicate.Finding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Finding) predicate.Finding {
	return predicate.Finding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Finding) predicate.Finding {
	return predicate.Finding(sql.NotPredicates(p))
}
