// Code generated by mockery. DO NOT EDIT.

// Regenerate with 'task gen-mocks' (or 'task gen').

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "librevita.org/internal/domain/identifier/model"

	usecase "librevita.org/internal/domain/identifier/usecase"
)

// MockSystemsService is an autogenerated mock type for the SystemsService type
type MockSystemsService struct {
	mock.Mock
}

type MockSystemsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemsService) EXPECT() *MockSystemsService_Expecter {
	return &MockSystemsService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createdBy, in
func (_m *MockSystemsService) Create(ctx context.Context, createdBy string, in usecase.SystemInput) (*model.IdentifierSystem, error) {
	ret := _m.Called(ctx, createdBy, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.IdentifierSystem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, usecase.SystemInput) (*model.IdentifierSystem, error)); ok {
		return rf(ctx, createdBy, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, usecase.SystemInput) *model.IdentifierSystem); ok {
		r0 = rf(ctx, createdBy, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IdentifierSystem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, usecase.SystemInput) error); ok {
		r1 = rf(ctx, createdBy, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemsService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSystemsService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createdBy string
//   - in usecase.SystemInput
func (_e *MockSystemsService_Expecter) Create(ctx interface{}, createdBy interface{}, in interface{}) *MockSystemsService_Create_Call {
	return &MockSystemsService_Create_Call{Call: _e.mock.On("Create", ctx, createdBy, in)}
}

func (_c *MockSystemsService_Create_Call) Run(run func(ctx context.Context, createdBy string, in usecase.SystemInput)) *MockSystemsService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(usecase.SystemInput))
	})
	return _c
}

func (_c *MockSystemsService_Create_Call) Return(_a0 *model.IdentifierSystem, _a1 error) *MockSystemsService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemsService_Create_Call) RunAndReturn(run func(context.Context, string, usecase.SystemInput) (*model.IdentifierSystem, error)) *MockSystemsService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockSystemsService) List(ctx context.Context) ([]*model.IdentifierSystem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.IdentifierSystem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.IdentifierSystem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.IdentifierSystem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.IdentifierSystem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemsService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSystemsService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemsService_Expecter) List(ctx interface{}) *MockSystemsService_List_Call {
	return &MockSystemsService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSystemsService_List_Call) Run(run func(ctx context.Context)) *MockSystemsService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemsService_List_Call) Return(_a0 []*model.IdentifierSystem, _a1 error) *MockSystemsService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemsService_List_Call) RunAndReturn(run func(context.Context) ([]*model.IdentifierSystem, error)) *MockSystemsService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function with given fields: ctx, id, active
func (_m *MockSystemsService) SetActive(ctx context.Context, id string, active bool) error {
	ret := _m.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for SetActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, active)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemsService_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockSystemsService_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - active bool
func (_e *MockSystemsService_Expecter) SetActive(ctx interface{}, id interface{}, active interface{}) *MockSystemsService_SetActive_Call {
	return &MockSystemsService_SetActive_Call{Call: _e.mock.On("SetActive", ctx, id, active)}
}

func (_c *MockSystemsService_SetActive_Call) Run(run func(ctx context.Context, id string, active bool)) *MockSystemsService_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockSystemsService_SetActive_Call) Return(_a0 error) *MockSystemsService_SetActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemsService_SetActive_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockSystemsService_SetActive_Call {
	_c.Call.Return(run)
	return _c
}

// SystemByID provides a mock function with given fields: ctx, id
func (_m *MockSystemsService) SystemByID(ctx context.Context, id string) (*model.IdentifierSystem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SystemByID")
	}

	var r0 *model.IdentifierSystem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.IdentifierSystem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.IdentifierSystem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IdentifierSystem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemsService_SystemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemByID'
type MockSystemsService_SystemByID_Call struct {
	*mock.Call
}

// SystemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSystemsService_Expecter) SystemByID(ctx interface{}, id interface{}) *MockSystemsService_SystemByID_Call {
	return &MockSystemsService_SystemByID_Call{Call: _e.mock.On("SystemByID", ctx, id)}
}

func (_c *MockSystemsService_SystemByID_Call) Run(run func(ctx context.Context, id string)) *MockSystemsService_SystemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSystemsService_SystemByID_Call) Return(_a0 *model.IdentifierSystem, _a1 error) *MockSystemsService_SystemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemsService_SystemByID_Call) RunAndReturn(run func(context.Context, string) (*model.IdentifierSystem, error)) *MockSystemsService_SystemByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *MockSystemsService) Update(ctx context.Context, id string, in usecase.SystemInput) (*model.IdentifierSystem, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.IdentifierSystem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, usecase.SystemInput) (*model.IdentifierSystem, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, usecase.SystemInput) *model.IdentifierSystem); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IdentifierSystem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, usecase.SystemInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemsService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSystemsService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in usecase.SystemInput
func (_e *MockSystemsService_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockSystemsService_Update_Call {
	return &MockSystemsService_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockSystemsService_Update_Call) Run(run func(ctx context.Context, id string, in usecase.SystemInput)) *MockSystemsService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(usecase.SystemInput))
	})
	return _c
}

func (_c *MockSystemsService_Update_Call) Return(_a0 *model.IdentifierSystem, _a1 error) *MockSystemsService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemsService_Update_Call) RunAndReturn(run func(context.Context, string, usecase.SystemInput) (*model.IdentifierSystem, error)) *MockSystemsService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemsService creates a new instance of MockSystemsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemsService {
	mock := &MockSystemsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
