// Code generated by mockery. DO NOT EDIT.

// Regenerate with 'task gen-mocks' (or 'task gen').

package usecasemocks

import mock "github.com/stretchr/testify/mock"

// MockStrategy is an autogenerated mock type for the Strategy type
type MockStrategy struct {
	mock.Mock
}

type MockStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStrategy) EXPECT() *MockStrategy_Expecter {
	return &MockStrategy_Expecter{mock: &_m.Mock}
}

// Detect provides a mock function with given fields: raw
func (_m *MockStrategy) Detect(raw string) bool {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Detect")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(raw)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockStrategy_Detect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detect'
type MockStrategy_Detect_Call struct {
	*mock.Call
}

// Detect is a helper method to define mock.On call
//   - raw string
func (_e *MockStrategy_Expecter) Detect(raw interface{}) *MockStrategy_Detect_Call {
	return &MockStrategy_Detect_Call{Call: _e.mock.On("Detect", raw)}
}

func (_c *MockStrategy_Detect_Call) Run(run func(raw string)) *MockStrategy_Detect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStrategy_Detect_Call) Return(_a0 bool) *MockStrategy_Detect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrategy_Detect_Call) RunAndReturn(run func(string) bool) *MockStrategy_Detect_Call {
	_c.Call.Return(run)
	return _c
}

// Normalize provides a mock function with given fields: raw
func (_m *MockStrategy) Normalize(raw string) (string, error) {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Normalize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(raw)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(raw)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStrategy_Normalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Normalize'
type MockStrategy_Normalize_Call struct {
	*mock.Call
}

// Normalize is a helper method to define mock.On call
//   - raw string
func (_e *MockStrategy_Expecter) Normalize(raw interface{}) *MockStrategy_Normalize_Call {
	return &MockStrategy_Normalize_Call{Call: _e.mock.On("Normalize", raw)}
}

func (_c *MockStrategy_Normalize_Call) Run(run func(raw string)) *MockStrategy_Normalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStrategy_Normalize_Call) Return(_a0 string, _a1 error) *MockStrategy_Normalize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStrategy_Normalize_Call) RunAndReturn(run func(string) (string, error)) *MockStrategy_Normalize_Call {
	_c.Call.Return(run)
	return _c
}

// System provides a mock function with no fields
func (_m *MockStrategy) System() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for System")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStrategy_System_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'System'
type MockStrategy_System_Call struct {
	*mock.Call
}

// System is a helper method to define mock.On call
func (_e *MockStrategy_Expecter) System() *MockStrategy_System_Call {
	return &MockStrategy_System_Call{Call: _e.mock.On("System")}
}

func (_c *MockStrategy_System_Call) Run(run func()) *MockStrategy_System_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStrategy_System_Call) Return(_a0 string) *MockStrategy_System_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrategy_System_Call) RunAndReturn(run func() string) *MockStrategy_System_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStrategy creates a new instance of MockStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStrategy {
	mock := &MockStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
