with-expecter: true
issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}mocks"
filename: "mock_{{.InterfaceName}}.go"
packages:
  librevita.org/internal/core/audit:
    config:
      all: false
      dir: "tests/mocks/core/audit"
    interfaces:
      Repository:
  librevita.org/internal/core/auth:
    config:
      all: false
      dir: "tests/mocks/core/auth"
    interfaces:
      SessionRepository:
  librevita.org/internal/core/crypto:
    config:
      all: false
      dir: "tests/mocks/core/crypto"
    interfaces:
      KeyVault:
  librevita.org/internal/core/policy:
    config:
      all: false
      dir: "tests/mocks/core/policy"
    interfaces:
      Repository:
  librevita.org/internal/core/storage:
    config:
      all: false
      dir: "tests/mocks/core/storage"
    interfaces:
      Store:
      IndexRepository:
  librevita.org/internal/domain/clinic/model:
    config:
      dir: "tests/mocks/domain/clinic/model"
  librevita.org/internal/domain/identifier/model:
    config:
      dir: "tests/mocks/domain/identifier/model"
  librevita.org/internal/domain/identifier/usecase:
    config:
      dir: "tests/mocks/domain/identifier/usecase"
  librevita.org/internal/domain/patient/model:
    config:
      dir: "tests/mocks/domain/patient/model"
  librevita.org/internal/domain/user/model:
    config:
      dir: "tests/mocks/domain/user/model"
