// Code generated by ent, DO NOT EDIT.

package problem

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/pkg/ident"
)

const (
	// Label holds the string label denoting the problem type in the database.
	Label = "problem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClinicID holds the string denoting the clinic_id field in the database.
	FieldClinicID = "clinic_id"
	// FieldPatientID holds the string denoting the patient_id field in the database.
	FieldPatientID = "patient_id"
	// FieldEpisodeID holds the string denoting the episode_id field in the database.
	FieldEpisodeID = "episode_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldClinicalStatus holds the string denoting the clinical_status field in the database.
	FieldClinicalStatus = "clinical_status"
	// FieldVerificationStatus holds the string denoting the verification_status field in the database.
	FieldVerificationStatus = "verification_status"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// FieldCodeSystem holds the string denoting the code_system field in the database.
	FieldCodeSystem = "code_system"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDisplay holds the string denoting the display field in the database.
	FieldDisplay = "display"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldCodeBlindIndex holds the string denoting the code_blind_index field in the database.
	FieldCodeBlindIndex = "code_blind_index"
	// EdgeClinic holds the string denoting the clinic edge name in mutations.
	EdgeClinic = "clinic"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeEpisode holds the string denoting the episode edge name in mutations.
	EdgeEpisode = "episode"
	// Table holds the table name of the problem in the database.
	Table = "problems"
	// ClinicTable is the table that holds the clinic relation/edge.
	ClinicTable = "problems"
	// ClinicInverseTable is the table name for the Clinic entity.
	// It exists in this package in order to avoid circular dependency with the "clinic" package.
	ClinicInverseTable = "clinics"
	// ClinicColumn is the table column denoting the clinic relation/edge.
	ClinicColumn = "clinic_id"
	// PatientTable is the table that holds the patient relation/edge.
	PatientTable = "problems"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// EpisodeTable is the table that holds the episode relation/edge.
	EpisodeTable = "problems"
	// EpisodeInverseTable is the table name for the Episode entity.
	// It exists in this package in order to avoid circular dependency with the "episode" package.
	EpisodeInverseTable = "episodes"
	// EpisodeColumn is the table column denoting the episode relation/edge.
	EpisodeColumn = "episode_id"
)

// Columns holds all SQL columns for problem fields.
var Columns = []string{
	FieldID,
	FieldClinicID,
	FieldPatientID,
	FieldEpisodeID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldClinicalStatus,
	FieldVerificationStatus,
	FieldCategory,
	FieldRank,
	FieldCodeSystem,
	FieldCode,
	FieldDisplay,
	FieldText,
	FieldCodeBlindIndex,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRank holds the default value on creation for the "rank" field.
	DefaultRank int
	// RankValidator is a validator for the "rank" field. It is called by the builders before save.
	RankValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ident.ProblemID
	// ValueScanner of all Problem fields.
	ValueScanner struct {
		CodeSystem field.TypeValueScanner[string]
		Code       field.TypeValueScanner[string]
		Display    field.TypeValueScanner[string]
		Text       field.TypeValueScanner[string]
	}
)

// ClinicalStatus defines the type for the "clinical_status" enum field.
type ClinicalStatus string

// ClinicalStatusActive is the default value of the ClinicalStatus enum.
const DefaultClinicalStatus = ClinicalStatusActive

// ClinicalStatus values.
const (
	ClinicalStatusActive   ClinicalStatus = "active"
	ClinicalStatusInactive ClinicalStatus = "inactive"
	ClinicalStatusResolved ClinicalStatus = "resolved"
)

func (cs ClinicalStatus) String() string {
	return string(cs)
}

// ClinicalStatusValidator is a validator for the "clinical_status" field enum values. It is called by the builders before save.
func ClinicalStatusValidator(cs ClinicalStatus) error {
	switch cs {
	case ClinicalStatusActive, ClinicalStatusInactive, ClinicalStatusResolved:
		return nil
	default:
		return fmt.Errorf("problem: invalid enum value for clinical_status field: %q", cs)
	}
}

// VerificationStatus defines the type for the "verification_status" enum field.
type VerificationStatus string

// VerificationStatusConfirmed is the default value of the VerificationStatus enum.
const DefaultVerificationStatus = VerificationStatusConfirmed

// VerificationStatus values.
const (
	VerificationStatusConfirmed VerificationStatus = "confirmed"
	VerificationStatusSuspected VerificationStatus = "suspected"
	VerificationStatusRefuted   VerificationStatus = "refuted"
	VerificationStatusError     VerificationStatus = "error"
)

func (vs VerificationStatus) String() string {
	return string(vs)
}

// VerificationStatusValidator is a validator for the "verification_status" field enum values. It is called by the builders before save.
func VerificationStatusValidator(vs VerificationStatus) error {
	switch vs {
	case VerificationStatusConfirmed, VerificationStatusSuspected, VerificationStatusRefuted, VerificationStatusError:
		return nil
	default:
		return fmt.Errorf("problem: invalid enum value for verification_status field: %q", vs)
	}
}

// Category defines the type for the "category" enum field.
type Category string

// CategoryEncounter is the default value of the Category enum.
const DefaultCategory = CategoryEncounter

// Category values.
const (
	CategoryEncounter Category = "encounter"
	CategoryList      Category = "list"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryEncounter, CategoryList:
		return nil
	default:
		return fmt.Errorf("problem: invalid enum value for category field: %q", c)
	}
}

// OrderOption defines the ordering options for the Problem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClinicID orders the results by the clinic_id field.
func ByClinicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClinicID, opts...).ToFunc()
}

// ByPatientID orders the results by the patient_id field.
func ByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientID, opts...).ToFunc()
}

// ByEpisodeID orders the results by the episode_id field.
func ByEpisodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpisodeID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClinicalStatus orders the results by the clinical_status field.
func ByClinicalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClinicalStatus, opts...).ToFunc()
}

// ByVerificationStatus orders the results by the verification_status field.
func ByVerificationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationStatus, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByRank orders the results by the rank field.
func ByRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRank, opts...).ToFunc()
}

// ByCodeSystem orders the results by the code_system field.
func ByCodeSystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeSystem, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDisplay orders the results by the display field.
func ByDisplay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplay, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByCodeBlindIndex orders the results by the code_blind_index field.
func ByCodeBlindIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeBlindIndex, opts...).ToFunc()
}

// ByClinicField orders the results by clinic field.
func ByClinicField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClinicStep(), sql.OrderByField(field, opts...))
	}
}

// ByPatientField orders the results by patient field.
func ByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPatientStep(), sql.OrderByField(field, opts...))
	}
}

// ByEpisodeField orders the results by episode field.
func ByEpisodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEpisodeStep(), sql.OrderByField(field, opts...))
	}
}
func newClinicStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClinicInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClinicTable, ClinicColumn),
	)
}
func newPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
	)
}
func newEpisodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EpisodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EpisodeTable, EpisodeColumn),
	)
}
