// Code generated by mockery. DO NOT EDIT.

// Regenerate with 'task gen-mocks' (or 'task gen').

package modelmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	ident "librevita.org/pkg/ident"

	model "librevita.org/internal/domain/user/model"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// CountUsersWithRole provides a mock function with given fields: ctx, roleID
func (_m *MockRoleRepository) CountUsersWithRole(ctx context.Context, roleID ident.RoleID) (int, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for CountUsersWithRole")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.RoleID) (int, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.RoleID) int); ok {
		r0 = rf(ctx, roleID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.RoleID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_CountUsersWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUsersWithRole'
type MockRoleRepository_CountUsersWithRole_Call struct {
	*mock.Call
}

// CountUsersWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID ident.RoleID
func (_e *MockRoleRepository_Expecter) CountUsersWithRole(ctx interface{}, roleID interface{}) *MockRoleRepository_CountUsersWithRole_Call {
	return &MockRoleRepository_CountUsersWithRole_Call{Call: _e.mock.On("CountUsersWithRole", ctx, roleID)}
}

func (_c *MockRoleRepository_CountUsersWithRole_Call) Run(run func(ctx context.Context, roleID ident.RoleID)) *MockRoleRepository_CountUsersWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.RoleID))
	})
	return _c
}

func (_c *MockRoleRepository_CountUsersWithRole_Call) Return(_a0 int, _a1 error) *MockRoleRepository_CountUsersWithRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_CountUsersWithRole_Call) RunAndReturn(run func(context.Context, ident.RoleID) (int, error)) *MockRoleRepository_CountUsersWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, r
func (_m *MockRoleRepository) Create(ctx context.Context, r *model.Role) (*model.Role, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) (*model.Role, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) *model.Role); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Role) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *model.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, r interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, r *model.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Role) (*model.Role, error)) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) Delete(ctx context.Context, id ident.RoleID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.RoleID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ident.RoleID
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id ident.RoleID)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.RoleID))
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(_a0 error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, ident.RoleID) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) GetByID(ctx context.Context, id ident.RoleID) (*model.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.RoleID) (*model.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.RoleID) *model.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.RoleID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ident.RoleID
func (_e *MockRoleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRoleRepository_GetByID_Call {
	return &MockRoleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRoleRepository_GetByID_Call) Run(run func(ctx context.Context, id ident.RoleID)) *MockRoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.RoleID))
	})
	return _c
}

func (_c *MockRoleRepository_GetByID_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_GetByID_Call) RunAndReturn(run func(context.Context, ident.RoleID) (*model.Role, error)) *MockRoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepository) GetByName(ctx context.Context, name string) (*model.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRoleRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockRoleRepository_GetByName_Call {
	return &MockRoleRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockRoleRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_GetByName_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*model.Role, error)) *MockRoleRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRoleRepository) List(ctx context.Context) ([]model.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) List(ctx interface{}) *MockRoleRepository_List_Call {
	return &MockRoleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoleRepository_List_Call) Run(run func(ctx context.Context)) *MockRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_List_Call) Return(_a0 []model.Role, _a1 error) *MockRoleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Role, error)) *MockRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SeedDefaults provides a mock function with given fields: ctx
func (_m *MockRoleRepository) SeedDefaults(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SeedDefaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_SeedDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedDefaults'
type MockRoleRepository_SeedDefaults_Call struct {
	*mock.Call
}

// SeedDefaults is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) SeedDefaults(ctx interface{}) *MockRoleRepository_SeedDefaults_Call {
	return &MockRoleRepository_SeedDefaults_Call{Call: _e.mock.On("SeedDefaults", ctx)}
}

func (_c *MockRoleRepository_SeedDefaults_Call) Run(run func(ctx context.Context)) *MockRoleRepository_SeedDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_SeedDefaults_Call) Return(_a0 error) *MockRoleRepository_SeedDefaults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_SeedDefaults_Call) RunAndReturn(run func(context.Context) error) *MockRoleRepository_SeedDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, r
func (_m *MockRoleRepository) Update(ctx context.Context, r *model.Role) (*model.Role, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) (*model.Role, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) *model.Role); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Role) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - r *model.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, r interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, r)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, r *model.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Role) (*model.Role, error)) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
