// Code generated by mockery. DO NOT EDIT.

// Regenerate with 'task gen-mocks' (or 'task gen').

package modelmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	ident "librevita.org/pkg/ident"

	model "librevita.org/internal/domain/user/model"
)

// MockSpecialtyRepository is an autogenerated mock type for the SpecialtyRepository type
type MockSpecialtyRepository struct {
	mock.Mock
}

type MockSpecialtyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecialtyRepository) EXPECT() *MockSpecialtyRepository_Expecter {
	return &MockSpecialtyRepository_Expecter{mock: &_m.Mock}
}

// CheckClinicScope provides a mock function with given fields: ctx, clinicID, specialtyIDs
func (_m *MockSpecialtyRepository) CheckClinicScope(ctx context.Context, clinicID ident.ClinicID, specialtyIDs []ident.SpecialtyID) (bool, error) {
	ret := _m.Called(ctx, clinicID, specialtyIDs)

	if len(ret) == 0 {
		panic("no return value specified for CheckClinicScope")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID, []ident.SpecialtyID) (bool, error)); ok {
		return rf(ctx, clinicID, specialtyIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID, []ident.SpecialtyID) bool); ok {
		r0 = rf(ctx, clinicID, specialtyIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.ClinicID, []ident.SpecialtyID) error); ok {
		r1 = rf(ctx, clinicID, specialtyIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpecialtyRepository_CheckClinicScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckClinicScope'
type MockSpecialtyRepository_CheckClinicScope_Call struct {
	*mock.Call
}

// CheckClinicScope is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID ident.ClinicID
//   - specialtyIDs []ident.SpecialtyID
func (_e *MockSpecialtyRepository_Expecter) CheckClinicScope(ctx interface{}, clinicID interface{}, specialtyIDs interface{}) *MockSpecialtyRepository_CheckClinicScope_Call {
	return &MockSpecialtyRepository_CheckClinicScope_Call{Call: _e.mock.On("CheckClinicScope", ctx, clinicID, specialtyIDs)}
}

func (_c *MockSpecialtyRepository_CheckClinicScope_Call) Run(run func(ctx context.Context, clinicID ident.ClinicID, specialtyIDs []ident.SpecialtyID)) *MockSpecialtyRepository_CheckClinicScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.ClinicID), args[2].([]ident.SpecialtyID))
	})
	return _c
}

func (_c *MockSpecialtyRepository_CheckClinicScope_Call) Return(_a0 bool, _a1 error) *MockSpecialtyRepository_CheckClinicScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpecialtyRepository_CheckClinicScope_Call) RunAndReturn(run func(context.Context, ident.ClinicID, []ident.SpecialtyID) (bool, error)) *MockSpecialtyRepository_CheckClinicScope_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, sp
func (_m *MockSpecialtyRepository) Create(ctx context.Context, sp *model.Specialty) (*model.Specialty, error) {
	ret := _m.Called(ctx, sp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Specialty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Specialty) (*model.Specialty, error)); ok {
		return rf(ctx, sp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Specialty) *model.Specialty); ok {
		r0 = rf(ctx, sp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Specialty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Specialty) error); ok {
		r1 = rf(ctx, sp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpecialtyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSpecialtyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sp *model.Specialty
func (_e *MockSpecialtyRepository_Expecter) Create(ctx interface{}, sp interface{}) *MockSpecialtyRepository_Create_Call {
	return &MockSpecialtyRepository_Create_Call{Call: _e.mock.On("Create", ctx, sp)}
}

func (_c *MockSpecialtyRepository_Create_Call) Run(run func(ctx context.Context, sp *model.Specialty)) *MockSpecialtyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Specialty))
	})
	return _c
}

func (_c *MockSpecialtyRepository_Create_Call) Return(_a0 *model.Specialty, _a1 error) *MockSpecialtyRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpecialtyRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Specialty) (*model.Specialty, error)) *MockSpecialtyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, clinicID, id
func (_m *MockSpecialtyRepository) Delete(ctx context.Context, clinicID ident.ClinicID, id ident.SpecialtyID) error {
	ret := _m.Called(ctx, clinicID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID, ident.SpecialtyID) error); ok {
		r0 = rf(ctx, clinicID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSpecialtyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSpecialtyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID ident.ClinicID
//   - id ident.SpecialtyID
func (_e *MockSpecialtyRepository_Expecter) Delete(ctx interface{}, clinicID interface{}, id interface{}) *MockSpecialtyRepository_Delete_Call {
	return &MockSpecialtyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, clinicID, id)}
}

func (_c *MockSpecialtyRepository_Delete_Call) Run(run func(ctx context.Context, clinicID ident.ClinicID, id ident.SpecialtyID)) *MockSpecialtyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.ClinicID), args[2].(ident.SpecialtyID))
	})
	return _c
}

func (_c *MockSpecialtyRepository_Delete_Call) Return(_a0 error) *MockSpecialtyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSpecialtyRepository_Delete_Call) RunAndReturn(run func(context.Context, ident.ClinicID, ident.SpecialtyID) error) *MockSpecialtyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByClinic provides a mock function with given fields: ctx, clinicID
func (_m *MockSpecialtyRepository) ListByClinic(ctx context.Context, clinicID ident.ClinicID) ([]model.Specialty, error) {
	ret := _m.Called(ctx, clinicID)

	if len(ret) == 0 {
		panic("no return value specified for ListByClinic")
	}

	var r0 []model.Specialty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID) ([]model.Specialty, error)); ok {
		return rf(ctx, clinicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID) []model.Specialty); ok {
		r0 = rf(ctx, clinicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Specialty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.ClinicID) error); ok {
		r1 = rf(ctx, clinicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpecialtyRepository_ListByClinic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByClinic'
type MockSpecialtyRepository_ListByClinic_Call struct {
	*mock.Call
}

// ListByClinic is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID ident.ClinicID
func (_e *MockSpecialtyRepository_Expecter) ListByClinic(ctx interface{}, clinicID interface{}) *MockSpecialtyRepository_ListByClinic_Call {
	return &MockSpecialtyRepository_ListByClinic_Call{Call: _e.mock.On("ListByClinic", ctx, clinicID)}
}

func (_c *MockSpecialtyRepository_ListByClinic_Call) Run(run func(ctx context.Context, clinicID ident.ClinicID)) *MockSpecialtyRepository_ListByClinic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.ClinicID))
	})
	return _c
}

func (_c *MockSpecialtyRepository_ListByClinic_Call) Return(_a0 []model.Specialty, _a1 error) *MockSpecialtyRepository_ListByClinic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpecialtyRepository_ListByClinic_Call) RunAndReturn(run func(context.Context, ident.ClinicID) ([]model.Specialty, error)) *MockSpecialtyRepository_ListByClinic_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockSpecialtyRepository) ListByUser(ctx context.Context, userID ident.UserID) ([]model.Specialty, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.Specialty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.UserID) ([]model.Specialty, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.UserID) []model.Specialty); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Specialty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpecialtyRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockSpecialtyRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID ident.UserID
func (_e *MockSpecialtyRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockSpecialtyRepository_ListByUser_Call {
	return &MockSpecialtyRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockSpecialtyRepository_ListByUser_Call) Run(run func(ctx context.Context, userID ident.UserID)) *MockSpecialtyRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.UserID))
	})
	return _c
}

func (_c *MockSpecialtyRepository_ListByUser_Call) Return(_a0 []model.Specialty, _a1 error) *MockSpecialtyRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpecialtyRepository_ListByUser_Call) RunAndReturn(run func(context.Context, ident.UserID) ([]model.Specialty, error)) *MockSpecialtyRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListPageByClinic provides a mock function with given fields: ctx, clinicID, limit, offset
func (_m *MockSpecialtyRepository) ListPageByClinic(ctx context.Context, clinicID ident.ClinicID, limit int, offset int) ([]model.Specialty, int64, error) {
	ret := _m.Called(ctx, clinicID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPageByClinic")
	}

	var r0 []model.Specialty
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID, int, int) ([]model.Specialty, int64, error)); ok {
		return rf(ctx, clinicID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ident.ClinicID, int, int) []model.Specialty); ok {
		r0 = rf(ctx, clinicID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Specialty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ident.ClinicID, int, int) int64); ok {
		r1 = rf(ctx, clinicID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ident.ClinicID, int, int) error); ok {
		r2 = rf(ctx, clinicID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSpecialtyRepository_ListPageByClinic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPageByClinic'
type MockSpecialtyRepository_ListPageByClinic_Call struct {
	*mock.Call
}

// ListPageByClinic is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID ident.ClinicID
//   - limit int
//   - offset int
func (_e *MockSpecialtyRepository_Expecter) ListPageByClinic(ctx interface{}, clinicID interface{}, limit interface{}, offset interface{}) *MockSpecialtyRepository_ListPageByClinic_Call {
	return &MockSpecialtyRepository_ListPageByClinic_Call{Call: _e.mock.On("ListPageByClinic", ctx, clinicID, limit, offset)}
}

func (_c *MockSpecialtyRepository_ListPageByClinic_Call) Run(run func(ctx context.Context, clinicID ident.ClinicID, limit int, offset int)) *MockSpecialtyRepository_ListPageByClinic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ident.ClinicID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockSpecialtyRepository_ListPageByClinic_Call) Return(_a0 []model.Specialty, _a1 int64, _a2 error) *MockSpecialtyRepository_ListPageByClinic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSpecialtyRepository_ListPageByClinic_Call) RunAndReturn(run func(context.Context, ident.ClinicID, int, int) ([]model.Specialty, int64, error)) *MockSpecialtyRepository_ListPageByClinic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpecialtyRepository creates a new instance of MockSpecialtyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecialtyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecialtyRepository {
	mock := &MockSpecialtyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
