// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/auditlog"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/predicate"
	"librevita.org/pkg/ident"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *AuditLogUpdate) SetClinicID(v ident.ClinicID) *AuditLogUpdate {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableClinicID(v *ident.ClinicID) *AuditLogUpdate {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// ClearClinicID clears the value of the "clinic_id" field.
func (_u *AuditLogUpdate) ClearClinicID() *AuditLogUpdate {
	_u.mutation.ClearClinicID()
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuditLogUpdate) SetActorID(v string) *AuditLogUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *AuditLogUpdate) ClearActorID() *AuditLogUpdate {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorEmail sets the "actor_email" field.
func (_u *AuditLogUpdate) SetActorEmail(v string) *AuditLogUpdate {
	_u.mutation.SetActorEmail(v)
	return _u
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorEmail(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorEmail(*v)
	}
	return _u
}

// ClearActorEmail clears the value of the "actor_email" field.
func (_u *AuditLogUpdate) ClearActorEmail() *AuditLogUpdate {
	_u.mutation.ClearActorEmail()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AuditLogUpdate) SetResource(v string) *AuditLogUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResource(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdate) SetResult(v auditlog.Result) *AuditLogUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResult(v *auditlog.Result) *AuditLogUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdate) SetIP(v string) *AuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIP(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdate) ClearIP() *AuditLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdate) SetRequestID(v string) *AuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRequestID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdate) ClearRequestID() *AuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditLogUpdate) SetDetail(v string) *AuditLogUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableDetail(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AuditLogUpdate) ClearDetail() *AuditLogUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *AuditLogUpdate) SetActorName(v string) *AuditLogUpdate {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorName(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *AuditLogUpdate) SetActorRole(v string) *AuditLogUpdate {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorRole(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdate) SetUserAgent(v string) *AuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserAgent(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *AuditLogUpdate) SetResourceName(v string) *AuditLogUpdate {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceName(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *AuditLogUpdate) SetSignature(v string) *AuditLogUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableSignature(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_u *AuditLogUpdate) SetClinic(v *Clinic) *AuditLogUpdate {
	return _u.SetClinicID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearClinic clears the "clinic" edge to the Clinic entity.
func (_u *AuditLogUpdate) ClearClinic() *AuditLogUpdate {
	_u.mutation.ClearClinic()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`record: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := auditlog.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`record: validator failed for field "AuditLog.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := auditlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`record: validator failed for field "AuditLog.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := auditlog.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`record: validator failed for field "AuditLog.signature": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeString, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(auditlog.FieldActorID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorEmail(); ok {
		_spec.SetField(auditlog.FieldActorEmail, field.TypeString, value)
	}
	if _u.mutation.ActorEmailCleared() {
		_spec.ClearField(auditlog.FieldActorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(auditlog.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(auditlog.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(auditlog.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(auditlog.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(auditlog.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(auditlog.FieldSignature, field.TypeString, value)
	}
	if _u.mutation.ClinicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ClinicTable,
			Columns: []string{auditlog.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ClinicTable,
			Columns: []string{auditlog.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetClinicID sets the "clinic_id" field.
func (_u *AuditLogUpdateOne) SetClinicID(v ident.ClinicID) *AuditLogUpdateOne {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableClinicID(v *ident.ClinicID) *AuditLogUpdateOne {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// ClearClinicID clears the value of the "clinic_id" field.
func (_u *AuditLogUpdateOne) ClearClinicID() *AuditLogUpdateOne {
	_u.mutation.ClearClinicID()
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuditLogUpdateOne) SetActorID(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *AuditLogUpdateOne) ClearActorID() *AuditLogUpdateOne {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorEmail sets the "actor_email" field.
func (_u *AuditLogUpdateOne) SetActorEmail(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorEmail(v)
	return _u
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorEmail(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorEmail(*v)
	}
	return _u
}

// ClearActorEmail clears the value of the "actor_email" field.
func (_u *AuditLogUpdateOne) ClearActorEmail() *AuditLogUpdateOne {
	_u.mutation.ClearActorEmail()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AuditLogUpdateOne) SetResource(v string) *AuditLogUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResource(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdateOne) SetResult(v auditlog.Result) *AuditLogUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResult(v *auditlog.Result) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdateOne) SetIP(v string) *AuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIP(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *AuditLogUpdateOne) ClearIP() *AuditLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdateOne) SetRequestID(v string) *AuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRequestID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdateOne) ClearRequestID() *AuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditLogUpdateOne) SetDetail(v string) *AuditLogUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableDetail(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AuditLogUpdateOne) ClearDetail() *AuditLogUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *AuditLogUpdateOne) SetActorName(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorName(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *AuditLogUpdateOne) SetActorRole(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorRole(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdateOne) SetUserAgent(v string) *AuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserAgent(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *AuditLogUpdateOne) SetResourceName(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceName(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *AuditLogUpdateOne) SetSignature(v string) *AuditLogUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableSignature(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_u *AuditLogUpdateOne) SetClinic(v *Clinic) *AuditLogUpdateOne {
	return _u.SetClinicID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearClinic clears the "clinic" edge to the Clinic entity.
func (_u *AuditLogUpdateOne) ClearClinic() *AuditLogUpdateOne {
	_u.mutation.ClearClinic()
	return _u
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`record: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := auditlog.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`record: validator failed for field "AuditLog.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := auditlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`record: validator failed for field "AuditLog.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := auditlog.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`record: validator failed for field "AuditLog.signature": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`record: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("record: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeString, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(auditlog.FieldActorID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorEmail(); ok {
		_spec.SetField(auditlog.FieldActorEmail, field.TypeString, value)
	}
	if _u.mutation.ActorEmailCleared() {
		_spec.ClearField(auditlog.FieldActorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(auditlog.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(auditlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(auditlog.FieldDetail, field.TypeString)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(auditlog.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(auditlog.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(auditlog.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(auditlog.FieldSignature, field.TypeString, value)
	}
	if _u.mutation.ClinicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ClinicTable,
			Columns: []string{auditlog.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ClinicTable,
			Columns: []string{auditlog.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
