// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/predicate"
)

// ClinicDelete is the builder for deleting a Clinic entity.
type ClinicDelete struct {
	config
	hooks    []Hook
	mutation *ClinicMutation
}

// Where appends a list predicates to the ClinicDelete builder.
func (_d *ClinicDelete) Where(ps ...predicate.Clinic) *ClinicDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClinicDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClinicDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClinicDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clinic.Table, sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClinicDeleteOne is the builder for deleting a single Clinic entity.
type ClinicDeleteOne struct {
	_d *ClinicDelete
}

// Where appends a list predicates to the ClinicDelete builder.
func (_d *ClinicDeleteOne) Where(ps ...predicate.Clinic) *ClinicDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClinicDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clinic.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClinicDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
