// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/patientidentifier"
	"librevita.org/internal/database/record/predicate"
)

// PatientIdentifierDelete is the builder for deleting a PatientIdentifier entity.
type PatientIdentifierDelete struct {
	config
	hooks    []Hook
	mutation *PatientIdentifierMutation
}

// Where appends a list predicates to the PatientIdentifierDelete builder.
func (_d *PatientIdentifierDelete) Where(ps ...predicate.PatientIdentifier) *PatientIdentifierDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PatientIdentifierDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PatientIdentifierDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PatientIdentifierDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(patientidentifier.Table, sqlgraph.NewFieldSpec(patientidentifier.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PatientIdentifierDeleteOne is the builder for deleting a single PatientIdentifier entity.
type PatientIdentifierDeleteOne struct {
	_d *PatientIdentifierDelete
}

// Where appends a list predicates to the PatientIdentifierDelete builder.
func (_d *PatientIdentifierDeleteOne) Where(ps ...predicate.PatientIdentifier) *PatientIdentifierDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PatientIdentifierDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{patientidentifier.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PatientIdentifierDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
