// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/identifiersystem"
	"librevita.org/internal/database/record/patient"
	"librevita.org/internal/database/record/patientidentifier"
	"librevita.org/internal/database/record/predicate"
	"librevita.org/pkg/ident"
)

// PatientIdentifierQuery is the builder for querying PatientIdentifier entities.
type PatientIdentifierQuery struct {
	config
	ctx                  *QueryContext
	order                []patientidentifier.OrderOption
	inters               []Interceptor
	predicates           []predicate.PatientIdentifier
	withClinic           *ClinicQuery
	withPatient          *PatientQuery
	withIdentifierSystem *IdentifierSystemQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PatientIdentifierQuery builder.
func (_q *PatientIdentifierQuery) Where(ps ...predicate.PatientIdentifier) *PatientIdentifierQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PatientIdentifierQuery) Limit(limit int) *PatientIdentifierQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PatientIdentifierQuery) Offset(offset int) *PatientIdentifierQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PatientIdentifierQuery) Unique(unique bool) *PatientIdentifierQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PatientIdentifierQuery) Order(o ...patientidentifier.OrderOption) *PatientIdentifierQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClinic chains the current query on the "clinic" edge.
func (_q *PatientIdentifierQuery) QueryClinic() *ClinicQuery {
	query := (&ClinicClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(patientidentifier.Table, patientidentifier.FieldID, selector),
			sqlgraph.To(clinic.Table, clinic.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, patientidentifier.ClinicTable, patientidentifier.ClinicColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPatient chains the current query on the "patient" edge.
func (_q *PatientIdentifierQuery) QueryPatient() *PatientQuery {
	query := (&PatientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(patientidentifier.Table, patientidentifier.FieldID, selector),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, patientidentifier.PatientTable, patientidentifier.PatientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIdentifierSystem chains the current query on the "identifier_system" edge.
func (_q *PatientIdentifierQuery) QueryIdentifierSystem() *IdentifierSystemQuery {
	query := (&IdentifierSystemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(patientidentifier.Table, patientidentifier.FieldID, selector),
			sqlgraph.To(identifiersystem.Table, identifiersystem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, patientidentifier.IdentifierSystemTable, patientidentifier.IdentifierSystemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PatientIdentifier entity from the query.
// Returns a *NotFoundError when no PatientIdentifier was found.
func (_q *PatientIdentifierQuery) First(ctx context.Context) (*PatientIdentifier, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{patientidentifier.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PatientIdentifierQuery) FirstX(ctx context.Context) *PatientIdentifier {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PatientIdentifier ID from the query.
// Returns a *NotFoundError when no PatientIdentifier ID was found.
func (_q *PatientIdentifierQuery) FirstID(ctx context.Context) (id ident.PatientIdentifierID, err error) {
	var ids []ident.PatientIdentifierID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{patientidentifier.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PatientIdentifierQuery) FirstIDX(ctx context.Context) ident.PatientIdentifierID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PatientIdentifier entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PatientIdentifier entity is found.
// Returns a *NotFoundError when no PatientIdentifier entities are found.
func (_q *PatientIdentifierQuery) Only(ctx context.Context) (*PatientIdentifier, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{patientidentifier.Label}
	default:
		return nil, &NotSingularError{patientidentifier.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PatientIdentifierQuery) OnlyX(ctx context.Context) *PatientIdentifier {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PatientIdentifier ID in the query.
// Returns a *NotSingularError when more than one PatientIdentifier ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PatientIdentifierQuery) OnlyID(ctx context.Context) (id ident.PatientIdentifierID, err error) {
	var ids []ident.PatientIdentifierID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{patientidentifier.Label}
	default:
		err = &NotSingularError{patientidentifier.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PatientIdentifierQuery) OnlyIDX(ctx context.Context) ident.PatientIdentifierID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PatientIdentifiers.
func (_q *PatientIdentifierQuery) All(ctx context.Context) ([]*PatientIdentifier, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PatientIdentifier, *PatientIdentifierQuery]()
	return withInterceptors[[]*PatientIdentifier](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PatientIdentifierQuery) AllX(ctx context.Context) []*PatientIdentifier {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PatientIdentifier IDs.
func (_q *PatientIdentifierQuery) IDs(ctx context.Context) (ids []ident.PatientIdentifierID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(patientidentifier.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PatientIdentifierQuery) IDsX(ctx context.Context) []ident.PatientIdentifierID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PatientIdentifierQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PatientIdentifierQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PatientIdentifierQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PatientIdentifierQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("record: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PatientIdentifierQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PatientIdentifierQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PatientIdentifierQuery) Clone() *PatientIdentifierQuery {
	if _q == nil {
		return nil
	}
	return &PatientIdentifierQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]patientidentifier.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.PatientIdentifier{}, _q.predicates...),
		withClinic:           _q.withClinic.Clone(),
		withPatient:          _q.withPatient.Clone(),
		withIdentifierSystem: _q.withIdentifierSystem.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClinic tells the query-builder to eager-load the nodes that are connected to
// the "clinic" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PatientIdentifierQuery) WithClinic(opts ...func(*ClinicQuery)) *PatientIdentifierQuery {
	query := (&ClinicClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClinic = query
	return _q
}

// WithPatient tells the query-builder to eager-load the nodes that are connected to
// the "patient" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PatientIdentifierQuery) WithPatient(opts ...func(*PatientQuery)) *PatientIdentifierQuery {
	query := (&PatientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPatient = query
	return _q
}

// WithIdentifierSystem tells the query-builder to eager-load the nodes that are connected to
// the "identifier_system" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PatientIdentifierQuery) WithIdentifierSystem(opts ...func(*IdentifierSystemQuery)) *PatientIdentifierQuery {
	query := (&IdentifierSystemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIdentifierSystem = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ClinicID ident.ClinicID `json:"clinic_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PatientIdentifier.Query().
//		GroupBy(patientidentifier.FieldClinicID).
//		Aggregate(record.Count()).
//		Scan(ctx, &v)
func (_q *PatientIdentifierQuery) GroupBy(field string, fields ...string) *PatientIdentifierGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PatientIdentifierGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = patientidentifier.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ClinicID ident.ClinicID `json:"clinic_id,omitempty"`
//	}
//
//	client.PatientIdentifier.Query().
//		Select(patientidentifier.FieldClinicID).
//		Scan(ctx, &v)
func (_q *PatientIdentifierQuery) Select(fields ...string) *PatientIdentifierSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PatientIdentifierSelect{PatientIdentifierQuery: _q}
	sbuild.label = patientidentifier.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PatientIdentifierSelect configured with the given aggregations.
func (_q *PatientIdentifierQuery) Aggregate(fns ...AggregateFunc) *PatientIdentifierSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PatientIdentifierQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("record: uninitialized interceptor (forgotten import record/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !patientidentifier.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("record: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PatientIdentifierQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PatientIdentifier, error) {
	var (
		nodes       = []*PatientIdentifier{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withClinic != nil,
			_q.withPatient != nil,
			_q.withIdentifierSystem != nil,
		}
	)
	if _q.withIdentifierSystem != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, patientidentifier.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PatientIdentifier).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PatientIdentifier{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClinic; query != nil {
		if err := _q.loadClinic(ctx, query, nodes, nil,
			func(n *PatientIdentifier, e *Clinic) { n.Edges.Clinic = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPatient; query != nil {
		if err := _q.loadPatient(ctx, query, nodes, nil,
			func(n *PatientIdentifier, e *Patient) { n.Edges.Patient = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIdentifierSystem; query != nil {
		if err := _q.loadIdentifierSystem(ctx, query, nodes, nil,
			func(n *PatientIdentifier, e *IdentifierSystem) { n.Edges.IdentifierSystem = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PatientIdentifierQuery) loadClinic(ctx context.Context, query *ClinicQuery, nodes []*PatientIdentifier, init func(*PatientIdentifier), assign func(*PatientIdentifier, *Clinic)) error {
	ids := make([]ident.ClinicID, 0, len(nodes))
	nodeids := make(map[ident.ClinicID][]*PatientIdentifier)
	for i := range nodes {
		fk := nodes[i].ClinicID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(clinic.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "clinic_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PatientIdentifierQuery) loadPatient(ctx context.Context, query *PatientQuery, nodes []*PatientIdentifier, init func(*PatientIdentifier), assign func(*PatientIdentifier, *Patient)) error {
	ids := make([]ident.PatientID, 0, len(nodes))
	nodeids := make(map[ident.PatientID][]*PatientIdentifier)
	for i := range nodes {
		fk := nodes[i].PatientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(patient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "patient_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PatientIdentifierQuery) loadIdentifierSystem(ctx context.Context, query *IdentifierSystemQuery, nodes []*PatientIdentifier, init func(*PatientIdentifier), assign func(*PatientIdentifier, *IdentifierSystem)) error {
	ids := make([]ident.IdentifierSystemID, 0, len(nodes))
	nodeids := make(map[ident.IdentifierSystemID][]*PatientIdentifier)
	for i := range nodes {
		if nodes[i].patient_identifier_identifier_system == nil {
			continue
		}
		fk := *nodes[i].patient_identifier_identifier_system
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(identifiersystem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "patient_identifier_identifier_system" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PatientIdentifierQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PatientIdentifierQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(patientidentifier.Table, patientidentifier.Columns, sqlgraph.NewFieldSpec(patientidentifier.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, patientidentifier.FieldID)
		for i := range fields {
			if fields[i] != patientidentifier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withClinic != nil {
			_spec.Node.AddColumnOnce(patientidentifier.FieldClinicID)
		}
		if _q.withPatient != nil {
			_spec.Node.AddColumnOnce(patientidentifier.FieldPatientID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PatientIdentifierQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(patientidentifier.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = patientidentifier.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PatientIdentifierGroupBy is the group-by builder for PatientIdentifier entities.
type PatientIdentifierGroupBy struct {
	selector
	build *PatientIdentifierQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PatientIdentifierGroupBy) Aggregate(fns ...AggregateFunc) *PatientIdentifierGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PatientIdentifierGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PatientIdentifierQuery, *PatientIdentifierGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PatientIdentifierGroupBy) sqlScan(ctx context.Context, root *PatientIdentifierQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PatientIdentifierSelect is the builder for selecting fields of PatientIdentifier entities.
type PatientIdentifierSelect struct {
	*PatientIdentifierQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PatientIdentifierSelect) Aggregate(fns ...AggregateFunc) *PatientIdentifierSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PatientIdentifierSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PatientIdentifierQuery, *PatientIdentifierSelect](ctx, _s.PatientIdentifierQuery, _s, _s.inters, v)
}

func (_s *PatientIdentifierSelect) sqlScan(ctx context.Context, root *PatientIdentifierQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
