// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/identifiersystem"
	"librevita.org/internal/database/record/patient"
	"librevita.org/internal/database/record/patientidentifier"
	"librevita.org/pkg/ident"
)

// PatientIdentifierCreate is the builder for creating a PatientIdentifier entity.
type PatientIdentifierCreate struct {
	config
	mutation *PatientIdentifierMutation
	hooks    []Hook
}

// SetClinicID sets the "clinic_id" field.
func (_c *PatientIdentifierCreate) SetClinicID(v ident.ClinicID) *PatientIdentifierCreate {
	_c.mutation.SetClinicID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PatientIdentifierCreate) SetCreatedAt(v time.Time) *PatientIdentifierCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PatientIdentifierCreate) SetNillableCreatedAt(v *time.Time) *PatientIdentifierCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PatientIdentifierCreate) SetUpdatedAt(v time.Time) *PatientIdentifierCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PatientIdentifierCreate) SetNillableUpdatedAt(v *time.Time) *PatientIdentifierCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPatientID sets the "patient_id" field.
func (_c *PatientIdentifierCreate) SetPatientID(v ident.PatientID) *PatientIdentifierCreate {
	_c.mutation.SetPatientID(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *PatientIdentifierCreate) SetSystem(v string) *PatientIdentifierCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetValueCiphertext sets the "value_ciphertext" field.
func (_c *PatientIdentifierCreate) SetValueCiphertext(v []byte) *PatientIdentifierCreate {
	_c.mutation.SetValueCiphertext(v)
	return _c
}

// SetBlindIndex sets the "blind_index" field.
func (_c *PatientIdentifierCreate) SetBlindIndex(v string) *PatientIdentifierCreate {
	_c.mutation.SetBlindIndex(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PatientIdentifierCreate) SetCreatedBy(v ident.UserID) *PatientIdentifierCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PatientIdentifierCreate) SetNillableCreatedBy(v *ident.UserID) *PatientIdentifierCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PatientIdentifierCreate) SetID(v ident.PatientIdentifierID) *PatientIdentifierCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PatientIdentifierCreate) SetNillableID(v *ident.PatientIdentifierID) *PatientIdentifierCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_c *PatientIdentifierCreate) SetClinic(v *Clinic) *PatientIdentifierCreate {
	return _c.SetClinicID(v.ID)
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_c *PatientIdentifierCreate) SetPatient(v *Patient) *PatientIdentifierCreate {
	return _c.SetPatientID(v.ID)
}

// SetIdentifierSystemID sets the "identifier_system" edge to the IdentifierSystem entity by ID.
func (_c *PatientIdentifierCreate) SetIdentifierSystemID(id ident.IdentifierSystemID) *PatientIdentifierCreate {
	_c.mutation.SetIdentifierSystemID(id)
	return _c
}

// SetNillableIdentifierSystemID sets the "identifier_system" edge to the IdentifierSystem entity by ID if the given value is not nil.
func (_c *PatientIdentifierCreate) SetNillableIdentifierSystemID(id *ident.IdentifierSystemID) *PatientIdentifierCreate {
	if id != nil {
		_c = _c.SetIdentifierSystemID(*id)
	}
	return _c
}

// SetIdentifierSystem sets the "identifier_system" edge to the IdentifierSystem entity.
func (_c *PatientIdentifierCreate) SetIdentifierSystem(v *IdentifierSystem) *PatientIdentifierCreate {
	return _c.SetIdentifierSystemID(v.ID)
}

// Mutation returns the PatientIdentifierMutation object of the builder.
func (_c *PatientIdentifierCreate) Mutation() *PatientIdentifierMutation {
	return _c.mutation
}

// Save creates the PatientIdentifier in the database.
func (_c *PatientIdentifierCreate) Save(ctx context.Context) (*PatientIdentifier, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatientIdentifierCreate) SaveX(ctx context.Context) *PatientIdentifier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientIdentifierCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientIdentifierCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatientIdentifierCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := patientidentifier.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := patientidentifier.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := patientidentifier.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatientIdentifierCreate) check() error {
	if _, ok := _c.mutation.ClinicID(); !ok {
		return &ValidationError{Name: "clinic_id", err: errors.New(`record: missing required field "PatientIdentifier.clinic_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`record: missing required field "PatientIdentifier.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`record: missing required field "PatientIdentifier.updated_at"`)}
	}
	if _, ok := _c.mutation.PatientID(); !ok {
		return &ValidationError{Name: "patient_id", err: errors.New(`record: missing required field "PatientIdentifier.patient_id"`)}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`record: missing required field "PatientIdentifier.system"`)}
	}
	if v, ok := _c.mutation.System(); ok {
		if err := patientidentifier.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`record: validator failed for field "PatientIdentifier.system": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValueCiphertext(); !ok {
		return &ValidationError{Name: "value_ciphertext", err: errors.New(`record: missing required field "PatientIdentifier.value_ciphertext"`)}
	}
	if v, ok := _c.mutation.ValueCiphertext(); ok {
		if err := patientidentifier.ValueCiphertextValidator(v); err != nil {
			return &ValidationError{Name: "value_ciphertext", err: fmt.Errorf(`record: validator failed for field "PatientIdentifier.value_ciphertext": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlindIndex(); !ok {
		return &ValidationError{Name: "blind_index", err: errors.New(`record: missing required field "PatientIdentifier.blind_index"`)}
	}
	if v, ok := _c.mutation.BlindIndex(); ok {
		if err := patientidentifier.BlindIndexValidator(v); err != nil {
			return &ValidationError{Name: "blind_index", err: fmt.Errorf(`record: validator failed for field "PatientIdentifier.blind_index": %w`, err)}
		}
	}
	if len(_c.mutation.ClinicIDs()) == 0 {
		return &ValidationError{Name: "clinic", err: errors.New(`record: missing required edge "PatientIdentifier.clinic"`)}
	}
	if len(_c.mutation.PatientIDs()) == 0 {
		return &ValidationError{Name: "patient", err: errors.New(`record: missing required edge "PatientIdentifier.patient"`)}
	}
	return nil
}

func (_c *PatientIdentifierCreate) sqlSave(ctx context.Context) (*PatientIdentifier, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ident.PatientIdentifierID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatientIdentifierCreate) createSpec() (*PatientIdentifier, *sqlgraph.CreateSpec) {
	var (
		_node = &PatientIdentifier{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patientidentifier.Table, sqlgraph.NewFieldSpec(patientidentifier.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(patientidentifier.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(patientidentifier.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(patientidentifier.FieldSystem, field.TypeString, value)
		_node.System = value
	}
	if value, ok := _c.mutation.ValueCiphertext(); ok {
		_spec.SetField(patientidentifier.FieldValueCiphertext, field.TypeBytes, value)
		_node.ValueCiphertext = value
	}
	if value, ok := _c.mutation.BlindIndex(); ok {
		_spec.SetField(patientidentifier.FieldBlindIndex, field.TypeString, value)
		_node.BlindIndex = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(patientidentifier.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if nodes := _c.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientidentifier.ClinicTable,
			Columns: []string{patientidentifier.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClinicID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientidentifier.PatientTable,
			Columns: []string{patientidentifier.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PatientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IdentifierSystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientidentifier.IdentifierSystemTable,
			Columns: []string{patientidentifier.IdentifierSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identifiersystem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.patient_identifier_identifier_system = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PatientIdentifierCreateBulk is the builder for creating many PatientIdentifier entities in bulk.
type PatientIdentifierCreateBulk struct {
	config
	err      error
	builders []*PatientIdentifierCreate
}

// Save creates the PatientIdentifier entities in the database.
func (_c *PatientIdentifierCreateBulk) Save(ctx context.Context) ([]*PatientIdentifier, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PatientIdentifier, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatientIdentifierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatientIdentifierCreateBulk) SaveX(ctx context.Context) []*PatientIdentifier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientIdentifierCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientIdentifierCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
