// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/episode"
	"librevita.org/internal/database/record/patient"
	"librevita.org/internal/database/record/planitem"
	"librevita.org/internal/database/record/predicate"
	"librevita.org/pkg/ident"
)

// PlanItemQuery is the builder for querying PlanItem entities.
type PlanItemQuery struct {
	config
	ctx         *QueryContext
	order       []planitem.OrderOption
	inters      []Interceptor
	predicates  []predicate.PlanItem
	withClinic  *ClinicQuery
	withPatient *PatientQuery
	withEpisode *EpisodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlanItemQuery builder.
func (_q *PlanItemQuery) Where(ps ...predicate.PlanItem) *PlanItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PlanItemQuery) Limit(limit int) *PlanItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PlanItemQuery) Offset(offset int) *PlanItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PlanItemQuery) Unique(unique bool) *PlanItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PlanItemQuery) Order(o ...planitem.OrderOption) *PlanItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryClinic chains the current query on the "clinic" edge.
func (_q *PlanItemQuery) QueryClinic() *ClinicQuery {
	query := (&ClinicClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(planitem.Table, planitem.FieldID, selector),
			sqlgraph.To(clinic.Table, clinic.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, planitem.ClinicTable, planitem.ClinicColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPatient chains the current query on the "patient" edge.
func (_q *PlanItemQuery) QueryPatient() *PatientQuery {
	query := (&PatientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(planitem.Table, planitem.FieldID, selector),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, planitem.PatientTable, planitem.PatientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEpisode chains the current query on the "episode" edge.
func (_q *PlanItemQuery) QueryEpisode() *EpisodeQuery {
	query := (&EpisodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(planitem.Table, planitem.FieldID, selector),
			sqlgraph.To(episode.Table, episode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, planitem.EpisodeTable, planitem.EpisodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PlanItem entity from the query.
// Returns a *NotFoundError when no PlanItem was found.
func (_q *PlanItemQuery) First(ctx context.Context) (*PlanItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{planitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PlanItemQuery) FirstX(ctx context.Context) *PlanItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PlanItem ID from the query.
// Returns a *NotFoundError when no PlanItem ID was found.
func (_q *PlanItemQuery) FirstID(ctx context.Context) (id ident.PlanItemID, err error) {
	var ids []ident.PlanItemID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{planitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PlanItemQuery) FirstIDX(ctx context.Context) ident.PlanItemID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PlanItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PlanItem entity is found.
// Returns a *NotFoundError when no PlanItem entities are found.
func (_q *PlanItemQuery) Only(ctx context.Context) (*PlanItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{planitem.Label}
	default:
		return nil, &NotSingularError{planitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PlanItemQuery) OnlyX(ctx context.Context) *PlanItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PlanItem ID in the query.
// Returns a *NotSingularError when more than one PlanItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PlanItemQuery) OnlyID(ctx context.Context) (id ident.PlanItemID, err error) {
	var ids []ident.PlanItemID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{planitem.Label}
	default:
		err = &NotSingularError{planitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PlanItemQuery) OnlyIDX(ctx context.Context) ident.PlanItemID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PlanItems.
func (_q *PlanItemQuery) All(ctx context.Context) ([]*PlanItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PlanItem, *PlanItemQuery]()
	return withInterceptors[[]*PlanItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PlanItemQuery) AllX(ctx context.Context) []*PlanItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PlanItem IDs.
func (_q *PlanItemQuery) IDs(ctx context.Context) (ids []ident.PlanItemID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(planitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PlanItemQuery) IDsX(ctx context.Context) []ident.PlanItemID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PlanItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PlanItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PlanItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PlanItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("record: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PlanItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlanItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PlanItemQuery) Clone() *PlanItemQuery {
	if _q == nil {
		return nil
	}
	return &PlanItemQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]planitem.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.PlanItem{}, _q.predicates...),
		withClinic:  _q.withClinic.Clone(),
		withPatient: _q.withPatient.Clone(),
		withEpisode: _q.withEpisode.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithClinic tells the query-builder to eager-load the nodes that are connected to
// the "clinic" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanItemQuery) WithClinic(opts ...func(*ClinicQuery)) *PlanItemQuery {
	query := (&ClinicClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withClinic = query
	return _q
}

// WithPatient tells the query-builder to eager-load the nodes that are connected to
// the "patient" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanItemQuery) WithPatient(opts ...func(*PatientQuery)) *PlanItemQuery {
	query := (&PatientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPatient = query
	return _q
}

// WithEpisode tells the query-builder to eager-load the nodes that are connected to
// the "episode" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlanItemQuery) WithEpisode(opts ...func(*EpisodeQuery)) *PlanItemQuery {
	query := (&EpisodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEpisode = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ClinicID ident.ClinicID `json:"clinic_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PlanItem.Query().
//		GroupBy(planitem.FieldClinicID).
//		Aggregate(record.Count()).
//		Scan(ctx, &v)
func (_q *PlanItemQuery) GroupBy(field string, fields ...string) *PlanItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlanItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = planitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ClinicID ident.ClinicID `json:"clinic_id,omitempty"`
//	}
//
//	client.PlanItem.Query().
//		Select(planitem.FieldClinicID).
//		Scan(ctx, &v)
func (_q *PlanItemQuery) Select(fields ...string) *PlanItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PlanItemSelect{PlanItemQuery: _q}
	sbuild.label = planitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlanItemSelect configured with the given aggregations.
func (_q *PlanItemQuery) Aggregate(fns ...AggregateFunc) *PlanItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PlanItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("record: uninitialized interceptor (forgotten import record/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !planitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("record: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PlanItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PlanItem, error) {
	var (
		nodes       = []*PlanItem{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withClinic != nil,
			_q.withPatient != nil,
			_q.withEpisode != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PlanItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PlanItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withClinic; query != nil {
		if err := _q.loadClinic(ctx, query, nodes, nil,
			func(n *PlanItem, e *Clinic) { n.Edges.Clinic = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPatient; query != nil {
		if err := _q.loadPatient(ctx, query, nodes, nil,
			func(n *PlanItem, e *Patient) { n.Edges.Patient = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEpisode; query != nil {
		if err := _q.loadEpisode(ctx, query, nodes, nil,
			func(n *PlanItem, e *Episode) { n.Edges.Episode = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PlanItemQuery) loadClinic(ctx context.Context, query *ClinicQuery, nodes []*PlanItem, init func(*PlanItem), assign func(*PlanItem, *Clinic)) error {
	ids := make([]ident.ClinicID, 0, len(nodes))
	nodeids := make(map[ident.ClinicID][]*PlanItem)
	for i := range nodes {
		fk := nodes[i].ClinicID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(clinic.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "clinic_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlanItemQuery) loadPatient(ctx context.Context, query *PatientQuery, nodes []*PlanItem, init func(*PlanItem), assign func(*PlanItem, *Patient)) error {
	ids := make([]ident.PatientID, 0, len(nodes))
	nodeids := make(map[ident.PatientID][]*PlanItem)
	for i := range nodes {
		fk := nodes[i].PatientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(patient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "patient_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlanItemQuery) loadEpisode(ctx context.Context, query *EpisodeQuery, nodes []*PlanItem, init func(*PlanItem), assign func(*PlanItem, *Episode)) error {
	ids := make([]ident.EpisodeID, 0, len(nodes))
	nodeids := make(map[ident.EpisodeID][]*PlanItem)
	for i := range nodes {
		fk := nodes[i].EpisodeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(episode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "episode_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PlanItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PlanItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(planitem.Table, planitem.Columns, sqlgraph.NewFieldSpec(planitem.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, planitem.FieldID)
		for i := range fields {
			if fields[i] != planitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withClinic != nil {
			_spec.Node.AddColumnOnce(planitem.FieldClinicID)
		}
		if _q.withPatient != nil {
			_spec.Node.AddColumnOnce(planitem.FieldPatientID)
		}
		if _q.withEpisode != nil {
			_spec.Node.AddColumnOnce(planitem.FieldEpisodeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PlanItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(planitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = planitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlanItemGroupBy is the group-by builder for PlanItem entities.
type PlanItemGroupBy struct {
	selector
	build *PlanItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PlanItemGroupBy) Aggregate(fns ...AggregateFunc) *PlanItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PlanItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlanItemQuery, *PlanItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PlanItemGroupBy) sqlScan(ctx context.Context, root *PlanItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlanItemSelect is the builder for selecting fields of PlanItem entities.
type PlanItemSelect struct {
	*PlanItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PlanItemSelect) Aggregate(fns ...AggregateFunc) *PlanItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PlanItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlanItemQuery, *PlanItemSelect](ctx, _s.PlanItemQuery, _s, _s.inters, v)
}

func (_s *PlanItemSelect) sqlScan(ctx context.Context, root *PlanItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
