// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/platformuser"
	"librevita.org/internal/database/record/predicate"
)

// PlatformUserUpdate is the builder for updating PlatformUser entities.
type PlatformUserUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformUserMutation
}

// Where appends a list predicates to the PlatformUserUpdate builder.
func (_u *PlatformUserUpdate) Where(ps ...predicate.PlatformUser) *PlatformUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUserUpdate) SetUpdatedAt(v time.Time) *PlatformUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *PlatformUserUpdate) SetEmail(v string) *PlatformUserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PlatformUserUpdate) SetNillableEmail(v *string) *PlatformUserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PlatformUserUpdate) SetPasswordHash(v string) *PlatformUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PlatformUserUpdate) SetNillablePasswordHash(v *string) *PlatformUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PlatformUserUpdate) SetDisplayName(v string) *PlatformUserUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PlatformUserUpdate) SetNillableDisplayName(v *string) *PlatformUserUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *PlatformUserUpdate) SetActive(v bool) *PlatformUserUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PlatformUserUpdate) SetNillableActive(v *bool) *PlatformUserUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the PlatformUserMutation object of the builder.
func (_u *PlatformUserUpdate) Mutation() *PlatformUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := platformuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`record: validator failed for field "PlatformUser.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := platformuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`record: validator failed for field "PlatformUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := platformuser.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`record: validator failed for field "PlatformUser.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformuser.Table, platformuser.Columns, sqlgraph.NewFieldSpec(platformuser.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(platformuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(platformuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(platformuser.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(platformuser.FieldActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformUserUpdateOne is the builder for updating a single PlatformUser entity.
type PlatformUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformUserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUserUpdateOne) SetUpdatedAt(v time.Time) *PlatformUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *PlatformUserUpdateOne) SetEmail(v string) *PlatformUserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PlatformUserUpdateOne) SetNillableEmail(v *string) *PlatformUserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PlatformUserUpdateOne) SetPasswordHash(v string) *PlatformUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PlatformUserUpdateOne) SetNillablePasswordHash(v *string) *PlatformUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PlatformUserUpdateOne) SetDisplayName(v string) *PlatformUserUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PlatformUserUpdateOne) SetNillableDisplayName(v *string) *PlatformUserUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *PlatformUserUpdateOne) SetActive(v bool) *PlatformUserUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PlatformUserUpdateOne) SetNillableActive(v *bool) *PlatformUserUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the PlatformUserMutation object of the builder.
func (_u *PlatformUserUpdateOne) Mutation() *PlatformUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the PlatformUserUpdate builder.
func (_u *PlatformUserUpdateOne) Where(ps ...predicate.PlatformUser) *PlatformUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformUserUpdateOne) Select(field string, fields ...string) *PlatformUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlatformUser entity.
func (_u *PlatformUserUpdateOne) Save(ctx context.Context) (*PlatformUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUserUpdateOne) SaveX(ctx context.Context) *PlatformUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := platformuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`record: validator failed for field "PlatformUser.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := platformuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`record: validator failed for field "PlatformUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := platformuser.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`record: validator failed for field "PlatformUser.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUserUpdateOne) sqlSave(ctx context.Context) (_node *PlatformUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformuser.Table, platformuser.Columns, sqlgraph.NewFieldSpec(platformuser.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`record: missing "PlatformUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformuser.FieldID)
		for _, f := range fields {
			if !platformuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("record: invalid field %q for query", f)}
			}
			if f != platformuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(platformuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(platformuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(platformuser.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(platformuser.FieldActive, field.TypeBool, value)
	}
	_node = &PlatformUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
