// Code generated by ent, DO NOT EDIT.

package record

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/staffchangerequest"
	"librevita.org/internal/database/record/user"
	"librevita.org/pkg/ident"
)

// StaffChangeRequestCreate is the builder for creating a StaffChangeRequest entity.
type StaffChangeRequestCreate struct {
	config
	mutation *StaffChangeRequestMutation
	hooks    []Hook
}

// SetClinicID sets the "clinic_id" field.
func (_c *StaffChangeRequestCreate) SetClinicID(v ident.ClinicID) *StaffChangeRequestCreate {
	_c.mutation.SetClinicID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StaffChangeRequestCreate) SetCreatedAt(v time.Time) *StaffChangeRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableCreatedAt(v *time.Time) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *StaffChangeRequestCreate) SetUserID(v ident.UserID) *StaffChangeRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *StaffChangeRequestCreate) SetRequestedBy(v ident.UserID) *StaffChangeRequestCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StaffChangeRequestCreate) SetStatus(v staffchangerequest.Status) *StaffChangeRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableStatus(v *staffchangerequest.Status) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetChanges sets the "changes" field.
func (_c *StaffChangeRequestCreate) SetChanges(v string) *StaffChangeRequestCreate {
	_c.mutation.SetChanges(v)
	return _c
}

// SetDecisionNote sets the "decision_note" field.
func (_c *StaffChangeRequestCreate) SetDecisionNote(v string) *StaffChangeRequestCreate {
	_c.mutation.SetDecisionNote(v)
	return _c
}

// SetNillableDecisionNote sets the "decision_note" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableDecisionNote(v *string) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetDecisionNote(*v)
	}
	return _c
}

// SetDecidedAt sets the "decided_at" field.
func (_c *StaffChangeRequestCreate) SetDecidedAt(v time.Time) *StaffChangeRequestCreate {
	_c.mutation.SetDecidedAt(v)
	return _c
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableDecidedAt(v *time.Time) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetDecidedAt(*v)
	}
	return _c
}

// SetDecidedBy sets the "decided_by" field.
func (_c *StaffChangeRequestCreate) SetDecidedBy(v ident.UserID) *StaffChangeRequestCreate {
	_c.mutation.SetDecidedBy(v)
	return _c
}

// SetNillableDecidedBy sets the "decided_by" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableDecidedBy(v *ident.UserID) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetDecidedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StaffChangeRequestCreate) SetID(v ident.StaffChangeRequestID) *StaffChangeRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableID(v *ident.StaffChangeRequestID) *StaffChangeRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_c *StaffChangeRequestCreate) SetClinic(v *Clinic) *StaffChangeRequestCreate {
	return _c.SetClinicID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *StaffChangeRequestCreate) SetUser(v *User) *StaffChangeRequestCreate {
	return _c.SetUserID(v.ID)
}

// SetRequesterID sets the "requester" edge to the User entity by ID.
func (_c *StaffChangeRequestCreate) SetRequesterID(id ident.UserID) *StaffChangeRequestCreate {
	_c.mutation.SetRequesterID(id)
	return _c
}

// SetRequester sets the "requester" edge to the User entity.
func (_c *StaffChangeRequestCreate) SetRequester(v *User) *StaffChangeRequestCreate {
	return _c.SetRequesterID(v.ID)
}

// SetDeciderID sets the "decider" edge to the User entity by ID.
func (_c *StaffChangeRequestCreate) SetDeciderID(id ident.UserID) *StaffChangeRequestCreate {
	_c.mutation.SetDeciderID(id)
	return _c
}

// SetNillableDeciderID sets the "decider" edge to the User entity by ID if the given value is not nil.
func (_c *StaffChangeRequestCreate) SetNillableDeciderID(id *ident.UserID) *StaffChangeRequestCreate {
	if id != nil {
		_c = _c.SetDeciderID(*id)
	}
	return _c
}

// SetDecider sets the "decider" edge to the User entity.
func (_c *StaffChangeRequestCreate) SetDecider(v *User) *StaffChangeRequestCreate {
	return _c.SetDeciderID(v.ID)
}

// Mutation returns the StaffChangeRequestMutation object of the builder.
func (_c *StaffChangeRequestCreate) Mutation() *StaffChangeRequestMutation {
	return _c.mutation
}

// Save creates the StaffChangeRequest in the database.
func (_c *StaffChangeRequestCreate) Save(ctx context.Context) (*StaffChangeRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StaffChangeRequestCreate) SaveX(ctx context.Context) *StaffChangeRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StaffChangeRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StaffChangeRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StaffChangeRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := staffchangerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := staffchangerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := staffchangerequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StaffChangeRequestCreate) check() error {
	if _, ok := _c.mutation.ClinicID(); !ok {
		return &ValidationError{Name: "clinic_id", err: errors.New(`record: missing required field "StaffChangeRequest.clinic_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`record: missing required field "StaffChangeRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`record: missing required field "StaffChangeRequest.user_id"`)}
	}
	if _, ok := _c.mutation.RequestedBy(); !ok {
		return &ValidationError{Name: "requested_by", err: errors.New(`record: missing required field "StaffChangeRequest.requested_by"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`record: missing required field "StaffChangeRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := staffchangerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`record: validator failed for field "StaffChangeRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Changes(); !ok {
		return &ValidationError{Name: "changes", err: errors.New(`record: missing required field "StaffChangeRequest.changes"`)}
	}
	if v, ok := _c.mutation.Changes(); ok {
		if err := staffchangerequest.ChangesValidator(v); err != nil {
			return &ValidationError{Name: "changes", err: fmt.Errorf(`record: validator failed for field "StaffChangeRequest.changes": %w`, err)}
		}
	}
	if len(_c.mutation.ClinicIDs()) == 0 {
		return &ValidationError{Name: "clinic", err: errors.New(`record: missing required edge "StaffChangeRequest.clinic"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`record: missing required edge "StaffChangeRequest.user"`)}
	}
	if len(_c.mutation.RequesterIDs()) == 0 {
		return &ValidationError{Name: "requester", err: errors.New(`record: missing required edge "StaffChangeRequest.requester"`)}
	}
	return nil
}

func (_c *StaffChangeRequestCreate) sqlSave(ctx context.Context) (*StaffChangeRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ident.StaffChangeRequestID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StaffChangeRequestCreate) createSpec() (*StaffChangeRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &StaffChangeRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(staffchangerequest.Table, sqlgraph.NewFieldSpec(staffchangerequest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(staffchangerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(staffchangerequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Changes(); ok {
		_spec.SetField(staffchangerequest.FieldChanges, field.TypeString, value)
		_node.Changes = value
	}
	if value, ok := _c.mutation.DecisionNote(); ok {
		_spec.SetField(staffchangerequest.FieldDecisionNote, field.TypeString, value)
		_node.DecisionNote = &value
	}
	if value, ok := _c.mutation.DecidedAt(); ok {
		_spec.SetField(staffchangerequest.FieldDecidedAt, field.TypeTime, value)
		_node.DecidedAt = &value
	}
	if nodes := _c.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staffchangerequest.ClinicTable,
			Columns: []string{staffchangerequest.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClinicID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staffchangerequest.UserTable,
			Columns: []string{staffchangerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   staffchangerequest.RequesterTable,
			Columns: []string{staffchangerequest.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeciderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   staffchangerequest.DeciderTable,
			Columns: []string{staffchangerequest.DeciderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DecidedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StaffChangeRequestCreateBulk is the builder for creating many StaffChangeRequest entities in bulk.
type StaffChangeRequestCreateBulk struct {
	config
	err      error
	builders []*StaffChangeRequestCreate
}

// Save creates the StaffChangeRequest entities in the database.
func (_c *StaffChangeRequestCreateBulk) Save(ctx context.Context) ([]*StaffChangeRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StaffChangeRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StaffChangeRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StaffChangeRequestCreateBulk) SaveX(ctx context.Context) []*StaffChangeRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StaffChangeRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StaffChangeRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
