// Code generated by ent, DO NOT EDIT.

package record

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"librevita.org/internal/database/record/clinic"
	"librevita.org/internal/database/record/storageobject"
	"librevita.org/internal/database/record/user"
	"librevita.org/pkg/ident"
)

// StorageObject is the model entity for the StorageObject schema.
type StorageObject struct {
	config `json:"-"`
	// ID of the ent.
	ID ident.StorageObjectID `json:"id,omitempty"`
	// Clinic tenant ID
	ClinicID ident.ClinicID `json:"clinic_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Content-addressed or path key in storage backend
	Key string `json:"key,omitempty"`
	// Domain context: patient, user, etc.
	Domain string `json:"domain,omitempty"`
	// Associated resource ID
	ResourceID string `json:"resource_id,omitempty"`
	// Original filename
	OriginalName string `json:"original_name,omitempty"`
	// MIME content type
	ContentType string `json:"content_type,omitempty"`
	// File size in bytes
	Size int64 `json:"size,omitempty"`
	// ETag returned by the storage backend
	Etag string `json:"etag,omitempty"`
	// Canonical BLAKE2b-256 digest of the payload
	Checksum string `json:"checksum,omitempty"`
	// User ID who uploaded the file
	CreatedBy ident.UserID `json:"created_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StorageObjectQuery when eager-loading is set.
	Edges        StorageObjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StorageObjectEdges holds the relations/edges for other nodes in the graph.
type StorageObjectEdges struct {
	// Clinic holds the value of the clinic edge.
	Clinic *Clinic `json:"clinic,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ClinicOrErr returns the Clinic value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageObjectEdges) ClinicOrErr() (*Clinic, error) {
	if e.Clinic != nil {
		return e.Clinic, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: clinic.Label}
	}
	return nil, &NotLoadedError{edge: "clinic"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageObjectEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StorageObject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storageobject.FieldClinicID:
			values[i] = new(ident.ClinicID)
		case storageobject.FieldID:
			values[i] = new(ident.StorageObjectID)
		case storageobject.FieldCreatedBy:
			values[i] = new(ident.UserID)
		case storageobject.FieldSize:
			values[i] = new(sql.NullInt64)
		case storageobject.FieldKey, storageobject.FieldDomain, storageobject.FieldResourceID, storageobject.FieldOriginalName, storageobject.FieldContentType, storageobject.FieldEtag, storageobject.FieldChecksum:
			values[i] = new(sql.NullString)
		case storageobject.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StorageObject fields.
func (_m *StorageObject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storageobject.FieldID:
			if value, ok := values[i].(*ident.StorageObjectID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case storageobject.FieldClinicID:
			if value, ok := values[i].(*ident.ClinicID); !ok {
				return fmt.Errorf("unexpected type %T for field clinic_id", values[i])
			} else if value != nil {
				_m.ClinicID = *value
			}
		case storageobject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case storageobject.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case storageobject.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case storageobject.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.String
			}
		case storageobject.FieldOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_name", values[i])
			} else if value.Valid {
				_m.OriginalName = value.String
			}
		case storageobject.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case storageobject.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case storageobject.FieldEtag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field etag", values[i])
			} else if value.Valid {
				_m.Etag = value.String
			}
		case storageobject.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		case storageobject.FieldCreatedBy:
			if value, ok := values[i].(*ident.UserID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StorageObject.
// This includes values selected through modifiers, order, etc.
func (_m *StorageObject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClinic queries the "clinic" edge of the StorageObject entity.
func (_m *StorageObject) QueryClinic() *ClinicQuery {
	return NewStorageObjectClient(_m.config).QueryClinic(_m)
}

// QueryCreator queries the "creator" edge of the StorageObject entity.
func (_m *StorageObject) QueryCreator() *UserQuery {
	return NewStorageObjectClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this StorageObject.
// Note that you need to call StorageObject.Unwrap() before calling this method if this StorageObject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StorageObject) Update() *StorageObjectUpdateOne {
	return NewStorageObjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StorageObject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StorageObject) Unwrap() *StorageObject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("record: StorageObject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StorageObject) String() string {
	var builder strings.Builder
	builder.WriteString("StorageObject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("clinic_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClinicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(_m.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("original_name=")
	builder.WriteString(_m.OriginalName)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("etag=")
	builder.WriteString(_m.Etag)
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// StorageObjects is a parsable slice of StorageObject.
type StorageObjects []*StorageObject
