-- Global LibreVita schema (SQLite).
-- Domain tables and triggers are defined here.
-- This is the schema source for sqlc (see sqlc.yaml).
-- Keep in sync with db/migrations/00002_auth.sql.
-- Primary keys are UUIDv7 TEXT generated by the application.

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE COLLATE nocase,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'patient'
    CHECK (role IN ('admin', 'physician', 'receptionist', 'patient')),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Server-side session revocation index, owned by internal/core/auth.
CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
);

-- Durable audit trail, owned by internal/core/audit.
-- See db/migrations/00003_audit.sql.
CREATE TABLE audit_log (
id          INTEGER PRIMARY KEY AUTOINCREMENT,
actor_id    TEXT,
actor_email TEXT,
action      TEXT    NOT NULL,
resource    TEXT    NOT NULL,
result      TEXT    NOT NULL CHECK (result IN ('success', 'failure')),
ip          TEXT,
request_id  TEXT,
detail      TEXT,
created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Clinic profile created during onboarding, owned by the clinic domain,
-- and the system metadata table. See db/migrations/00004_onboarding.sql.
CREATE TABLE clinics (
id          TEXT    PRIMARY KEY,
name        TEXT    NOT NULL,
tax_id      TEXT,
phone       TEXT,
email       TEXT,
street      TEXT,
city        TEXT,
state       TEXT,
postal_code TEXT,
country     TEXT    NOT NULL DEFAULT 'BR',
timezone    TEXT    NOT NULL DEFAULT 'America/Sao_Paulo',
created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE meta (
key        TEXT    PRIMARY KEY,
value      TEXT    NOT NULL,
updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Dynamic CEL authorization policies, owned by internal/core/policy.
-- See db/migrations/00005_policy.sql and 00006_policy_version.sql.
CREATE TABLE policies (
id         TEXT    PRIMARY KEY,
name       TEXT    NOT NULL UNIQUE,
expression TEXT    NOT NULL,
updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE policy_versions (
id               INTEGER PRIMARY KEY AUTOINCREMENT,
policy_id        TEXT    NOT NULL REFERENCES policies(id) ON DELETE RESTRICT,
expression       TEXT    NOT NULL,
changed_by       TEXT,
changed_by_email TEXT,
origin           TEXT    NOT NULL DEFAULT 'system'
CHECK (origin IN ('seed', 'admin', 'system')),
created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ',
'now'))
);
