-- Global LibreVita schema (SQLite).
-- Domain tables and triggers are defined here.
-- This is the schema source for sqlc (see sqlc.yaml).
-- The sessions table belongs to internal/core/auth and is intentionally
-- absent; keep it in sync with db/migrations/00002_auth.sql.
-- Primary keys are UUIDv7 TEXT generated by the application.

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE COLLATE nocase,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'patient'
    CHECK (role IN ('admin', 'physician', 'receptionist', 'patient')),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Durable audit trail, owned by internal/core/audit.
-- See db/migrations/00003_audit.sql.
CREATE TABLE audit_log (
id          INTEGER PRIMARY KEY AUTOINCREMENT,
actor_id    TEXT,
actor_email TEXT,
action      TEXT    NOT NULL,
resource    TEXT    NOT NULL,
result      TEXT    NOT NULL CHECK (result IN ('success', 'failure')),
ip          TEXT,
request_id  TEXT,
detail      TEXT,
created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
