// Code generated by mockery. DO NOT EDIT.

// Regenerate with 'task gen-mocks' (or 'task gen').

package policymocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	policy "librevita.org/internal/core/policy"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Count(ctx interface{}) *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockRepository_Count_Call) Run(run func(ctx context.Context)) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(_a0 int64, _a1 error) *MockRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// History provides a mock function with given fields: ctx, name, limit
func (_m *MockRepository) History(ctx context.Context, name string, limit int) ([]policy.PolicyVersionRow, error) {
	ret := _m.Called(ctx, name, limit)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []policy.PolicyVersionRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]policy.PolicyVersionRow, error)); ok {
		return rf(ctx, name, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []policy.PolicyVersionRow); ok {
		r0 = rf(ctx, name, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]policy.PolicyVersionRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, name, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MockRepository_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - limit int
func (_e *MockRepository_Expecter) History(ctx interface{}, name interface{}, limit interface{}) *MockRepository_History_Call {
	return &MockRepository_History_Call{Call: _e.mock.On("History", ctx, name, limit)}
}

func (_c *MockRepository_History_Call) Run(run func(ctx context.Context, name string, limit int)) *MockRepository_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_History_Call) Return(_a0 []policy.PolicyVersionRow, _a1 error) *MockRepository_History_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_History_Call) RunAndReturn(run func(context.Context, string, int) ([]policy.PolicyVersionRow, error)) *MockRepository_History_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRepository) List(ctx context.Context) ([]policy.PolicyRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []policy.PolicyRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]policy.PolicyRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []policy.PolicyRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]policy.PolicyRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) List(ctx interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []policy.PolicyRow, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context) ([]policy.PolicyRow, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SeedDefaults provides a mock function with given fields: ctx, defaults
func (_m *MockRepository) SeedDefaults(ctx context.Context, defaults map[string]string) error {
	ret := _m.Called(ctx, defaults)

	if len(ret) == 0 {
		panic("no return value specified for SeedDefaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) error); ok {
		r0 = rf(ctx, defaults)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SeedDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedDefaults'
type MockRepository_SeedDefaults_Call struct {
	*mock.Call
}

// SeedDefaults is a helper method to define mock.On call
//   - ctx context.Context
//   - defaults map[string]string
func (_e *MockRepository_Expecter) SeedDefaults(ctx interface{}, defaults interface{}) *MockRepository_SeedDefaults_Call {
	return &MockRepository_SeedDefaults_Call{Call: _e.mock.On("SeedDefaults", ctx, defaults)}
}

func (_c *MockRepository_SeedDefaults_Call) Run(run func(ctx context.Context, defaults map[string]string)) *MockRepository_SeedDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockRepository_SeedDefaults_Call) Return(_a0 error) *MockRepository_SeedDefaults_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SeedDefaults_Call) RunAndReturn(run func(context.Context, map[string]string) error) *MockRepository_SeedDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, name, expression, actor, origin
func (_m *MockRepository) Set(ctx context.Context, name string, expression string, actor policy.Actor, origin string) error {
	ret := _m.Called(ctx, name, expression, actor, origin)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, policy.Actor, string) error); ok {
		r0 = rf(ctx, name, expression, actor, origin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - expression string
//   - actor policy.Actor
//   - origin string
func (_e *MockRepository_Expecter) Set(ctx interface{}, name interface{}, expression interface{}, actor interface{}, origin interface{}) *MockRepository_Set_Call {
	return &MockRepository_Set_Call{Call: _e.mock.On("Set", ctx, name, expression, actor, origin)}
}

func (_c *MockRepository_Set_Call) Run(run func(ctx context.Context, name string, expression string, actor policy.Actor, origin string)) *MockRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(policy.Actor), args[4].(string))
	})
	return _c
}

func (_c *MockRepository_Set_Call) Return(_a0 error) *MockRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Set_Call) RunAndReturn(run func(context.Context, string, string, policy.Actor, string) error) *MockRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
