// Code generated by ent, DO NOT EDIT.

package patientidentifier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"librevita.org/pkg/ident"
)

const (
	// Label holds the string label denoting the patientidentifier type in the database.
	Label = "patient_identifier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClinicID holds the string denoting the clinic_id field in the database.
	FieldClinicID = "clinic_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPatientID holds the string denoting the patient_id field in the database.
	FieldPatientID = "patient_id"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldValueCiphertext holds the string denoting the value_ciphertext field in the database.
	FieldValueCiphertext = "value_ciphertext"
	// FieldBlindIndex holds the string denoting the blind_index field in the database.
	FieldBlindIndex = "blind_index"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// EdgeClinic holds the string denoting the clinic edge name in mutations.
	EdgeClinic = "clinic"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeIdentifierSystem holds the string denoting the identifier_system edge name in mutations.
	EdgeIdentifierSystem = "identifier_system"
	// Table holds the table name of the patientidentifier in the database.
	Table = "patient_identifiers"
	// ClinicTable is the table that holds the clinic relation/edge.
	ClinicTable = "patient_identifiers"
	// ClinicInverseTable is the table name for the Clinic entity.
	// It exists in this package in order to avoid circular dependency with the "clinic" package.
	ClinicInverseTable = "clinics"
	// ClinicColumn is the table column denoting the clinic relation/edge.
	ClinicColumn = "clinic_id"
	// PatientTable is the table that holds the patient relation/edge.
	PatientTable = "patient_identifiers"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// IdentifierSystemTable is the table that holds the identifier_system relation/edge.
	IdentifierSystemTable = "patient_identifiers"
	// IdentifierSystemInverseTable is the table name for the IdentifierSystem entity.
	// It exists in this package in order to avoid circular dependency with the "identifiersystem" package.
	IdentifierSystemInverseTable = "identifier_systems"
	// IdentifierSystemColumn is the table column denoting the identifier_system relation/edge.
	IdentifierSystemColumn = "patient_identifier_identifier_system"
)

// Columns holds all SQL columns for patientidentifier fields.
var Columns = []string{
	FieldID,
	FieldClinicID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPatientID,
	FieldSystem,
	FieldValueCiphertext,
	FieldBlindIndex,
	FieldCreatedBy,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "patient_identifiers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"identifier_system_identifiers",
	"patient_identifier_identifier_system",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SystemValidator is a validator for the "system" field. It is called by the builders before save.
	SystemValidator func(string) error
	// ValueCiphertextValidator is a validator for the "value_ciphertext" field. It is called by the builders before save.
	ValueCiphertextValidator func([]byte) error
	// BlindIndexValidator is a validator for the "blind_index" field. It is called by the builders before save.
	BlindIndexValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ident.PatientIdentifierID
)

// OrderOption defines the ordering options for the PatientIdentifier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClinicID orders the results by the clinic_id field.
func ByClinicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClinicID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPatientID orders the results by the patient_id field.
func ByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientID, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// ByBlindIndex orders the results by the blind_index field.
func ByBlindIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlindIndex, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByClinicField orders the results by clinic field.
func ByClinicField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClinicStep(), sql.OrderByField(field, opts...))
	}
}

// ByPatientField orders the results by patient field.
func ByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPatientStep(), sql.OrderByField(field, opts...))
	}
}

// ByIdentifierSystemField orders the results by identifier_system field.
func ByIdentifierSystemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIdentifierSystemStep(), sql.OrderByField(field, opts...))
	}
}
func newClinicStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClinicInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClinicTable, ClinicColumn),
	)
}
func newPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
	)
}
func newIdentifierSystemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IdentifierSystemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, IdentifierSystemTable, IdentifierSystemColumn),
	)
}
