// Code generated by ent, DO NOT EDIT.

package episode

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"librevita.org/internal/database/record/predicate"
	"librevita.org/pkg/ident"
)

// ID filters vertices based on their ID field.
func ID(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldID, id))
}

// ClinicID applies equality check predicate on the "clinic_id" field. It's identical to ClinicIDEQ.
func ClinicID(v ident.ClinicID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldClinicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdatedAt, v))
}

// PatientID applies equality check predicate on the "patient_id" field. It's identical to PatientIDEQ.
func PatientID(v ident.PatientID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPatientID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v ident.UserID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUserID, v))
}

// AppointmentID applies equality check predicate on the "appointment_id" field. It's identical to AppointmentIDEQ.
func AppointmentID(v ident.AppointmentID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAppointmentID, v))
}

// PredecessorID applies equality check predicate on the "predecessor_id" field. It's identical to PredecessorIDEQ.
func PredecessorID(v ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPredecessorID, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldOccurredAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldEndedAt, v))
}

// Subjective applies equality check predicate on the "subjective" field. It's identical to SubjectiveEQ.
func Subjective(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldSubjective, vc), err)
}

// Objective applies equality check predicate on the "objective" field. It's identical to ObjectiveEQ.
func Objective(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldObjective, vc), err)
}

// Assessment applies equality check predicate on the "assessment" field. It's identical to AssessmentEQ.
func Assessment(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldAssessment, vc), err)
}

// Plan applies equality check predicate on the "plan" field. It's identical to PlanEQ.
func Plan(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldPlan, vc), err)
}

// ClinicIDEQ applies the EQ predicate on the "clinic_id" field.
func ClinicIDEQ(v ident.ClinicID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldClinicID, v))
}

// ClinicIDNEQ applies the NEQ predicate on the "clinic_id" field.
func ClinicIDNEQ(v ident.ClinicID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldClinicID, v))
}

// ClinicIDIn applies the In predicate on the "clinic_id" field.
func ClinicIDIn(vs ...ident.ClinicID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldClinicID, vs...))
}

// ClinicIDNotIn applies the NotIn predicate on the "clinic_id" field.
func ClinicIDNotIn(vs ...ident.ClinicID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldClinicID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldUpdatedAt, v))
}

// PatientIDEQ applies the EQ predicate on the "patient_id" field.
func PatientIDEQ(v ident.PatientID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPatientID, v))
}

// PatientIDNEQ applies the NEQ predicate on the "patient_id" field.
func PatientIDNEQ(v ident.PatientID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldPatientID, v))
}

// PatientIDIn applies the In predicate on the "patient_id" field.
func PatientIDIn(vs ...ident.PatientID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldPatientID, vs...))
}

// PatientIDNotIn applies the NotIn predicate on the "patient_id" field.
func PatientIDNotIn(vs ...ident.PatientID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldPatientID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v ident.UserID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v ident.UserID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...ident.UserID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...ident.UserID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldUserID, vs...))
}

// AppointmentIDEQ applies the EQ predicate on the "appointment_id" field.
func AppointmentIDEQ(v ident.AppointmentID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldAppointmentID, v))
}

// AppointmentIDNEQ applies the NEQ predicate on the "appointment_id" field.
func AppointmentIDNEQ(v ident.AppointmentID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldAppointmentID, v))
}

// AppointmentIDIn applies the In predicate on the "appointment_id" field.
func AppointmentIDIn(vs ...ident.AppointmentID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldAppointmentID, vs...))
}

// AppointmentIDNotIn applies the NotIn predicate on the "appointment_id" field.
func AppointmentIDNotIn(vs ...ident.AppointmentID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldAppointmentID, vs...))
}

// AppointmentIDIsNil applies the IsNil predicate on the "appointment_id" field.
func AppointmentIDIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldAppointmentID))
}

// AppointmentIDNotNil applies the NotNil predicate on the "appointment_id" field.
func AppointmentIDNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldAppointmentID))
}

// PredecessorIDEQ applies the EQ predicate on the "predecessor_id" field.
func PredecessorIDEQ(v ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPredecessorID, v))
}

// PredecessorIDNEQ applies the NEQ predicate on the "predecessor_id" field.
func PredecessorIDNEQ(v ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldPredecessorID, v))
}

// PredecessorIDIn applies the In predicate on the "predecessor_id" field.
func PredecessorIDIn(vs ...ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldPredecessorID, vs...))
}

// PredecessorIDNotIn applies the NotIn predicate on the "predecessor_id" field.
func PredecessorIDNotIn(vs ...ident.EpisodeID) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldPredecessorID, vs...))
}

// PredecessorIDIsNil applies the IsNil predicate on the "predecessor_id" field.
func PredecessorIDIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldPredecessorID))
}

// PredecessorIDNotNil applies the NotNil predicate on the "predecessor_id" field.
func PredecessorIDNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldPredecessorID))
}

// EpisodeTypeEQ applies the EQ predicate on the "episode_type" field.
func EpisodeTypeEQ(v EpisodeType) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldEpisodeType, v))
}

// EpisodeTypeNEQ applies the NEQ predicate on the "episode_type" field.
func EpisodeTypeNEQ(v EpisodeType) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldEpisodeType, v))
}

// EpisodeTypeIn applies the In predicate on the "episode_type" field.
func EpisodeTypeIn(vs ...EpisodeType) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldEpisodeType, vs...))
}

// EpisodeTypeNotIn applies the NotIn predicate on the "episode_type" field.
func EpisodeTypeNotIn(vs ...EpisodeType) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldEpisodeType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldStatus, vs...))
}

// ClassEQ applies the EQ predicate on the "class" field.
func ClassEQ(v Class) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldClass, v))
}

// ClassNEQ applies the NEQ predicate on the "class" field.
func ClassNEQ(v Class) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldClass, v))
}

// ClassIn applies the In predicate on the "class" field.
func ClassIn(vs ...Class) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldClass, vs...))
}

// ClassNotIn applies the NotIn predicate on the "class" field.
func ClassNotIn(vs ...Class) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldClass, vs...))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldOccurredAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldEndedAt))
}

// SubjectiveEQ applies the EQ predicate on the "subjective" field.
func SubjectiveEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldSubjective, vc), err)
}

// SubjectiveNEQ applies the NEQ predicate on the "subjective" field.
func SubjectiveNEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldNEQ(FieldSubjective, vc), err)
}

// SubjectiveIn applies the In predicate on the "subjective" field.
func SubjectiveIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Subjective.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldIn(FieldSubjective, v...), err)
}

// SubjectiveNotIn applies the NotIn predicate on the "subjective" field.
func SubjectiveNotIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Subjective.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldNotIn(FieldSubjective, v...), err)
}

// SubjectiveGT applies the GT predicate on the "subjective" field.
func SubjectiveGT(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGT(FieldSubjective, vc), err)
}

// SubjectiveGTE applies the GTE predicate on the "subjective" field.
func SubjectiveGTE(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGTE(FieldSubjective, vc), err)
}

// SubjectiveLT applies the LT predicate on the "subjective" field.
func SubjectiveLT(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLT(FieldSubjective, vc), err)
}

// SubjectiveLTE applies the LTE predicate on the "subjective" field.
func SubjectiveLTE(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLTE(FieldSubjective, vc), err)
}

// SubjectiveContains applies the Contains predicate on the "subjective" field.
func SubjectiveContains(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("subjective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContains(FieldSubjective, vcs), err)
}

// SubjectiveHasPrefix applies the HasPrefix predicate on the "subjective" field.
func SubjectiveHasPrefix(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("subjective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasPrefix(FieldSubjective, vcs), err)
}

// SubjectiveHasSuffix applies the HasSuffix predicate on the "subjective" field.
func SubjectiveHasSuffix(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("subjective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasSuffix(FieldSubjective, vcs), err)
}

// SubjectiveIsNil applies the IsNil predicate on the "subjective" field.
func SubjectiveIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldSubjective))
}

// SubjectiveNotNil applies the NotNil predicate on the "subjective" field.
func SubjectiveNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldSubjective))
}

// SubjectiveEqualFold applies the EqualFold predicate on the "subjective" field.
func SubjectiveEqualFold(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("subjective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldEqualFold(FieldSubjective, vcs), err)
}

// SubjectiveContainsFold applies the ContainsFold predicate on the "subjective" field.
func SubjectiveContainsFold(v string) predicate.Episode {
	vc, err := ValueScanner.Subjective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("subjective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContainsFold(FieldSubjective, vcs), err)
}

// ObjectiveEQ applies the EQ predicate on the "objective" field.
func ObjectiveEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldObjective, vc), err)
}

// ObjectiveNEQ applies the NEQ predicate on the "objective" field.
func ObjectiveNEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldNEQ(FieldObjective, vc), err)
}

// ObjectiveIn applies the In predicate on the "objective" field.
func ObjectiveIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Objective.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldIn(FieldObjective, v...), err)
}

// ObjectiveNotIn applies the NotIn predicate on the "objective" field.
func ObjectiveNotIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Objective.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldNotIn(FieldObjective, v...), err)
}

// ObjectiveGT applies the GT predicate on the "objective" field.
func ObjectiveGT(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGT(FieldObjective, vc), err)
}

// ObjectiveGTE applies the GTE predicate on the "objective" field.
func ObjectiveGTE(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGTE(FieldObjective, vc), err)
}

// ObjectiveLT applies the LT predicate on the "objective" field.
func ObjectiveLT(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLT(FieldObjective, vc), err)
}

// ObjectiveLTE applies the LTE predicate on the "objective" field.
func ObjectiveLTE(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLTE(FieldObjective, vc), err)
}

// ObjectiveContains applies the Contains predicate on the "objective" field.
func ObjectiveContains(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("objective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContains(FieldObjective, vcs), err)
}

// ObjectiveHasPrefix applies the HasPrefix predicate on the "objective" field.
func ObjectiveHasPrefix(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("objective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasPrefix(FieldObjective, vcs), err)
}

// ObjectiveHasSuffix applies the HasSuffix predicate on the "objective" field.
func ObjectiveHasSuffix(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("objective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasSuffix(FieldObjective, vcs), err)
}

// ObjectiveIsNil applies the IsNil predicate on the "objective" field.
func ObjectiveIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldObjective))
}

// ObjectiveNotNil applies the NotNil predicate on the "objective" field.
func ObjectiveNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldObjective))
}

// ObjectiveEqualFold applies the EqualFold predicate on the "objective" field.
func ObjectiveEqualFold(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("objective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldEqualFold(FieldObjective, vcs), err)
}

// ObjectiveContainsFold applies the ContainsFold predicate on the "objective" field.
func ObjectiveContainsFold(v string) predicate.Episode {
	vc, err := ValueScanner.Objective.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("objective value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContainsFold(FieldObjective, vcs), err)
}

// AssessmentEQ applies the EQ predicate on the "assessment" field.
func AssessmentEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldAssessment, vc), err)
}

// AssessmentNEQ applies the NEQ predicate on the "assessment" field.
func AssessmentNEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldNEQ(FieldAssessment, vc), err)
}

// AssessmentIn applies the In predicate on the "assessment" field.
func AssessmentIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Assessment.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldIn(FieldAssessment, v...), err)
}

// AssessmentNotIn applies the NotIn predicate on the "assessment" field.
func AssessmentNotIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Assessment.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldNotIn(FieldAssessment, v...), err)
}

// AssessmentGT applies the GT predicate on the "assessment" field.
func AssessmentGT(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGT(FieldAssessment, vc), err)
}

// AssessmentGTE applies the GTE predicate on the "assessment" field.
func AssessmentGTE(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGTE(FieldAssessment, vc), err)
}

// AssessmentLT applies the LT predicate on the "assessment" field.
func AssessmentLT(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLT(FieldAssessment, vc), err)
}

// AssessmentLTE applies the LTE predicate on the "assessment" field.
func AssessmentLTE(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLTE(FieldAssessment, vc), err)
}

// AssessmentContains applies the Contains predicate on the "assessment" field.
func AssessmentContains(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("assessment value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContains(FieldAssessment, vcs), err)
}

// AssessmentHasPrefix applies the HasPrefix predicate on the "assessment" field.
func AssessmentHasPrefix(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("assessment value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasPrefix(FieldAssessment, vcs), err)
}

// AssessmentHasSuffix applies the HasSuffix predicate on the "assessment" field.
func AssessmentHasSuffix(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("assessment value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasSuffix(FieldAssessment, vcs), err)
}

// AssessmentIsNil applies the IsNil predicate on the "assessment" field.
func AssessmentIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldAssessment))
}

// AssessmentNotNil applies the NotNil predicate on the "assessment" field.
func AssessmentNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldAssessment))
}

// AssessmentEqualFold applies the EqualFold predicate on the "assessment" field.
func AssessmentEqualFold(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("assessment value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldEqualFold(FieldAssessment, vcs), err)
}

// AssessmentContainsFold applies the ContainsFold predicate on the "assessment" field.
func AssessmentContainsFold(v string) predicate.Episode {
	vc, err := ValueScanner.Assessment.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("assessment value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContainsFold(FieldAssessment, vcs), err)
}

// PlanEQ applies the EQ predicate on the "plan" field.
func PlanEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldEQ(FieldPlan, vc), err)
}

// PlanNEQ applies the NEQ predicate on the "plan" field.
func PlanNEQ(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldNEQ(FieldPlan, vc), err)
}

// PlanIn applies the In predicate on the "plan" field.
func PlanIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Plan.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldIn(FieldPlan, v...), err)
}

// PlanNotIn applies the NotIn predicate on the "plan" field.
func PlanNotIn(vs ...string) predicate.Episode {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.Plan.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.EpisodeOrErr(sql.FieldNotIn(FieldPlan, v...), err)
}

// PlanGT applies the GT predicate on the "plan" field.
func PlanGT(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGT(FieldPlan, vc), err)
}

// PlanGTE applies the GTE predicate on the "plan" field.
func PlanGTE(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldGTE(FieldPlan, vc), err)
}

// PlanLT applies the LT predicate on the "plan" field.
func PlanLT(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLT(FieldPlan, vc), err)
}

// PlanLTE applies the LTE predicate on the "plan" field.
func PlanLTE(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	return predicate.EpisodeOrErr(sql.FieldLTE(FieldPlan, vc), err)
}

// PlanContains applies the Contains predicate on the "plan" field.
func PlanContains(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("plan value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContains(FieldPlan, vcs), err)
}

// PlanHasPrefix applies the HasPrefix predicate on the "plan" field.
func PlanHasPrefix(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("plan value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasPrefix(FieldPlan, vcs), err)
}

// PlanHasSuffix applies the HasSuffix predicate on the "plan" field.
func PlanHasSuffix(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("plan value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldHasSuffix(FieldPlan, vcs), err)
}

// PlanIsNil applies the IsNil predicate on the "plan" field.
func PlanIsNil() predicate.Episode {
	return predicate.Episode(sql.FieldIsNull(FieldPlan))
}

// PlanNotNil applies the NotNil predicate on the "plan" field.
func PlanNotNil() predicate.Episode {
	return predicate.Episode(sql.FieldNotNull(FieldPlan))
}

// PlanEqualFold applies the EqualFold predicate on the "plan" field.
func PlanEqualFold(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("plan value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldEqualFold(FieldPlan, vcs), err)
}

// PlanContainsFold applies the ContainsFold predicate on the "plan" field.
func PlanContainsFold(v string) predicate.Episode {
	vc, err := ValueScanner.Plan.Value(v)
	vcs, ok := vc.(string)
	if err == nil && !ok {
		err = fmt.Errorf("plan value is not a string: %T", vc)
	}
	return predicate.EpisodeOrErr(sql.FieldContainsFold(FieldPlan, vcs), err)
}

// HasClinic applies the HasEdge predicate on the "clinic" edge.
func HasClinic() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClinicTable, ClinicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicWith applies the HasEdge predicate on the "clinic" edge with a given conditions (other predicates).
func HasClinicWith(preds ...predicate.Clinic) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newClinicStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPatient applies the HasEdge predicate on the "patient" edge.
func HasPatient() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientWith applies the HasEdge predicate on the "patient" edge with a given conditions (other predicates).
func HasPatientWith(preds ...predicate.Patient) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newPatientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAppointment applies the HasEdge predicate on the "appointment" edge.
func HasAppointment() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppointmentTable, AppointmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppointmentWith applies the HasEdge predicate on the "appointment" edge with a given conditions (other predicates).
func HasAppointmentWith(preds ...predicate.Appointment) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newAppointmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAmendment applies the HasEdge predicate on the "amendment" edge.
func HasAmendment() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, AmendmentTable, AmendmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAmendmentWith applies the HasEdge predicate on the "amendment" edge with a given conditions (other predicates).
func HasAmendmentWith(preds ...predicate.Episode) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newAmendmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPredecessor applies the HasEdge predicate on the "predecessor" edge.
func HasPredecessor() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PredecessorTable, PredecessorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPredecessorWith applies the HasEdge predicate on the "predecessor" edge with a given conditions (other predicates).
func HasPredecessorWith(preds ...predicate.Episode) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newPredecessorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFindings applies the HasEdge predicate on the "findings" edge.
func HasFindings() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FindingsTable, FindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFindingsWith applies the HasEdge predicate on the "findings" edge with a given conditions (other predicates).
func HasFindingsWith(preds ...predicate.Finding) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newFindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProblems applies the HasEdge predicate on the "problems" edge.
func HasProblems() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProblemsTable, ProblemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemsWith applies the HasEdge predicate on the "problems" edge with a given conditions (other predicates).
func HasProblemsWith(preds ...predicate.Problem) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newProblemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlanItems applies the HasEdge predicate on the "plan_items" edge.
func HasPlanItems() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlanItemsTable, PlanItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanItemsWith applies the HasEdge predicate on the "plan_items" edge with a given conditions (other predicates).
func HasPlanItemsWith(preds ...predicate.PlanItem) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newPlanItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.NotPredicates(p))
}
