package fle

import (
	"strings"
	"text/template"

	"entgo.io/ent/entc/gen"
)

// Template is the official Ent extension template for Field-Level Encryption (FLE).
// It generates compile-time, type-safe mutation hooks and query interceptors
// directly via Ent's code generation engine.
var Template = gen.MustParse(gen.NewTemplate("fle_hooks").
	Funcs(template.FuncMap{
		"lower":              strings.ToLower,
		"hasEncryptedFields": hasEncryptedFields,
		"encryptedFields":    encryptedFieldsOf,
		"isSearchable":       isSearchableField,
		"isNameField":        isNameField,
		"hasTokenIndex":      hasTokenIndex,
		"normalizerFunc":     normalizerFunc,
	}).
	Parse(fleTemplate))

func isNameField(f *gen.Field) bool {
	if ann, ok := f.Annotations[AnnotationName]; ok {
		if m, ok := ann.(map[string]any); ok {
			if norm, ok := m["normalizer"].(string); ok && strings.ToLower(norm) == "name" {
				return true
			}
			if norm, ok := m["Normalizer"].(string); ok && strings.ToLower(norm) == "name" {
				return true
			}
		}
	}
	return false
}

func hasTokenIndex(n *gen.Type, f *gen.Field) bool {
	tokenName := f.Name + "_token_index"
	for _, fld := range n.Fields {
		if fld.Name == tokenName {
			return true
		}
	}
	return false
}

func normalizerFunc(f *gen.Field) string {
	if ann, ok := f.Annotations[AnnotationName]; ok {
		if m, ok := ann.(map[string]any); ok {
			if norm, ok := m["normalizer"].(string); ok && norm != "" {
				switch strings.ToLower(norm) {
				case "phone":
					return "normalize.Phone"
				case "email":
					return "normalize.Email"
				case "document":
					return "normalize.Document"
				default:
					return "normalize.Text"
				}
			}
			if norm, ok := m["Normalizer"].(string); ok && norm != "" {
				switch strings.ToLower(norm) {
				case "phone":
					return "normalize.Phone"
				case "email":
					return "normalize.Email"
				case "document":
					return "normalize.Document"
				default:
					return "normalize.Text"
				}
			}
		}
	}
	return "normalize.Text"
}

func isSearchableField(f *gen.Field) bool {
	if ann, ok := f.Annotations[AnnotationName]; ok {
		if m, ok := ann.(map[string]any); ok {
			if s, ok := m["searchable"].(bool); ok && s {
				return true
			}
			if s, ok := m["Searchable"].(bool); ok && s {
				return true
			}
		}
	}
	return false
}

func isEncryptedField(f *gen.Field) bool {
	if strings.HasSuffix(f.Name, "_blind_index") {
		return false
	}
	if f.HasValueScanner() {
		return true
	}
	if ann, ok := f.Annotations[AnnotationName]; ok {
		if m, ok := ann.(map[string]any); ok {
			if e, ok := m["encrypted"].(bool); ok && e {
				return true
			}
			if e, ok := m["Encrypted"].(bool); ok && e {
				return true
			}
			if s, ok := m["searchable"].(bool); ok && s {
				return true
			}
			if s, ok := m["Searchable"].(bool); ok && s {
				return true
			}
		}
	}
	return false
}

func hasEncryptedFields(n *gen.Type) bool {
	for _, f := range n.Fields {
		if isEncryptedField(f) {
			return true
		}
	}
	return false
}

func encryptedFieldsOf(n *gen.Type) []*gen.Field {
	var out []*gen.Field
	for _, f := range n.Fields {
		if isEncryptedField(f) {
			out = append(out, f)
		}
	}
	return out
}

const fleTemplate = `
{{ define "fle_hooks" }}

{{- /* Top-level file header generated by Ent */}}
{{ $pkg := $.Package }}
{{ $nodes := $.Nodes }}

{{ template "header" $ }}

import (
	"context"

	"librevita.org/internal/core/crypto"
	"librevita.org/internal/core/database/fle"
	"librevita.org/internal/core/normalize"
)

{{ range $n := $nodes }}
{{- if hasEncryptedFields $n }}
// Decrypt{{ $n.Name }} decrypts all encrypted fields of {{ $n.Name }} in place without reflection.
func Decrypt{{ $n.Name }}(ctx context.Context, enc crypto.Encryptor, entity *{{ $n.Name }}) error {
	if entity == nil || enc == nil {
		return nil
	}
	aad := fle.ResolveAAD(ctx)
	{{- range $f := encryptedFields $n }}
	{{- if $f.Nillable }}
	if entity.{{ $f.StructField }} != nil && crypto.IsCiphertextString(*entity.{{ $f.StructField }}) {
		if dec, err := fle.DecryptString(enc, []byte(*entity.{{ $f.StructField }}), aad); err == nil {
			*entity.{{ $f.StructField }} = dec
		}
	}
	{{- else }}
	if crypto.IsCiphertextString(entity.{{ $f.StructField }}) {
		if dec, err := fle.DecryptString(enc, []byte(entity.{{ $f.StructField }}), aad); err == nil {
			entity.{{ $f.StructField }} = dec
		}
	}
	{{- end }}
	{{- end }}
	return nil
}

func encrypt{{ $n.Name }}Mutation(ctx context.Context, hasher crypto.Hasher, enc crypto.Encryptor, m *{{ $n.MutationName }}) error {
	aad := fle.ResolveAAD(ctx)
	{{- range $f := encryptedFields $n }}
	{{- if isSearchable $f }}
	if val, ok := m.{{ $f.MutationGet }}(); ok && val != "" && !crypto.IsCiphertextString(val) && hasher != nil {
		{{- if isNameField $f }}
		{{- if hasTokenIndex $n $f }}
		tokens := normalize.NameTokens(val)
		tokenHashes := make([]string, 0, len(tokens))
		for _, tok := range tokens {
			if h, err := hasher.BlindIndex("{{ lower $n.Name }}.token", tok); err == nil {
				tokenHashes = append(tokenHashes, h)
			}
		}
		m.Set{{ $f.StructField }}TokenIndex(tokenHashes)
		{{- end }}
		{{- else }}
		domainTag := "{{ lower $n.Name }}.{{ $f.Name }}"
		if customDomain, _, ok := fle.SearchableFieldFromContext(ctx); ok && customDomain != "" {
			domainTag = customDomain
		}
		normalized := {{ normalizerFunc $f }}(val)
		if blindHash, err := hasher.BlindIndex(domainTag, normalized); err == nil {
			m.Set{{ $f.StructField }}BlindIndex(blindHash)
		}
		{{- end }}
	}
	{{- end }}
	if val, ok := m.{{ $f.MutationGet }}(); ok && val != "" && !crypto.IsCiphertextString(val) && enc != nil {
		if ctBytes, err := fle.EncryptString(enc, val, aad); err == nil {
			m.{{ $f.MutationSet }}(string(ctBytes))
		}
	}
	{{- end }}
	return nil
}
{{- end }}
{{- end }}

// FLEMutationHook returns an ent.Hook that computes blind indexes and encrypts fields
// before database persistence in a 100% type-safe manner without reflection.
func FLEMutationHook(hasher crypto.Hasher, defaultEnc crypto.Encryptor) Hook {
	return func(next Mutator) Mutator {
		return MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			if !m.Op().Is(OpCreate | OpUpdate | OpUpdateOne) {
				return next.Mutate(ctx, m)
			}
			enc, err := fle.ResolveEncryptor(ctx, defaultEnc)
			if err != nil {
				return nil, err
			}

			switch mut := m.(type) {
			{{- range $n := $nodes }}
			{{- if hasEncryptedFields $n }}
			case *{{ $n.MutationName }}:
				_ = encrypt{{ $n.Name }}Mutation(ctx, hasher, enc, mut)
			{{- end }}
			{{- end }}
			}

			val, err := next.Mutate(ctx, m)
			if err != nil {
				return nil, err
			}

			if enc != nil && val != nil {
				switch v := val.(type) {
				{{- range $n := $nodes }}
				{{- if hasEncryptedFields $n }}
				case *{{ $n.Name }}:
					_ = Decrypt{{ $n.Name }}(ctx, enc, v)
				{{- end }}
				{{- end }}
				}
			}

			return val, nil
		})
	}
}

// FLEDecryptionInterceptor returns an ent.Interceptor that transparently decrypts
// all queried entities in a 100% type-safe manner without reflection.
func FLEDecryptionInterceptor(defaultEnc crypto.Encryptor) Interceptor {
	return InterceptFunc(func(next Querier) Querier {
		return QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
			val, err := next.Query(ctx, q)
			if err != nil {
				return nil, err
			}
			enc, err := fle.ResolveEncryptor(ctx, defaultEnc)
			if err != nil || enc == nil || val == nil {
				return val, err
			}

			switch v := val.(type) {
			{{- range $n := $nodes }}
			{{- if hasEncryptedFields $n }}
			case *{{ $n.Name }}:
				_ = Decrypt{{ $n.Name }}(ctx, enc, v)
			case []*{{ $n.Name }}:
				for _, item := range v {
					_ = Decrypt{{ $n.Name }}(ctx, enc, item)
				}
			{{- end }}
			{{- end }}
			}

			return val, nil
		})
	})
}

{{ end }}
`
